-- PETATOE v9 Enterprise Localization Center - Phase 1
-- Safe foundation: language registry, keys, approved values, queue, and history.

begin;

create table if not exists public.localization_languages (
  code text primary key check (code ~ '^[a-z]{2,3}(-[A-Z]{2})?$'),
  name text not null,
  english_name text not null,
  direction text not null default 'ltr' check (direction in ('ltr','rtl')),
  locale text not null,
  is_enabled boolean not null default false,
  is_default boolean not null default false,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists localization_languages_single_default_idx
  on public.localization_languages (is_default) where is_default = true;

create table if not exists public.localization_keys (
  id bigint generated by default as identity primary key,
  translation_key text not null unique,
  module text not null default 'global',
  source_text text,
  description text,
  is_system boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.localization_values (
  id bigint generated by default as identity primary key,
  key_id bigint not null references public.localization_keys(id) on delete cascade,
  language_code text not null references public.localization_languages(code) on delete cascade,
  translated_text text not null,
  status text not null default 'approved' check (status in ('draft','pending','approved','rejected')),
  version integer not null default 1,
  approved_by uuid,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (key_id, language_code)
);

create table if not exists public.localization_queue (
  id bigint generated by default as identity primary key,
  translation_key text,
  source_language text not null default 'ar',
  source_text text not null,
  target_language text not null,
  suggested_text text,
  module text not null default 'runtime',
  status text not null default 'pending' check (status in ('pending','reviewed','approved','rejected')),
  occurrence_count integer not null default 1,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  reviewed_by uuid,
  reviewed_at timestamptz,
  unique (source_text, source_language, target_language, module)
);

create table if not exists public.localization_history (
  id bigint generated by default as identity primary key,
  value_id bigint references public.localization_values(id) on delete set null,
  translation_key text not null,
  language_code text not null,
  old_text text,
  new_text text,
  action text not null,
  changed_by uuid,
  changed_at timestamptz not null default now()
);

create or replace view public.localization_approved_values
with (security_invoker = true) as
select k.translation_key, v.language_code, v.translated_text, k.module, v.version
from public.localization_values v
join public.localization_keys k on k.id = v.key_id
join public.localization_languages l on l.code = v.language_code
where v.status = 'approved' and k.is_active = true and l.is_enabled = true;

insert into public.localization_languages(code,name,english_name,direction,locale,is_enabled,is_default,sort_order)
values
  ('ar','العربية','Arabic','rtl','ar-SA',true,true,10),
  ('en','English','English','ltr','en-SA',true,false,20),
  ('fil','Filipino','Filipino','ltr','fil-PH',false,false,30)
on conflict (code) do update set
  name=excluded.name,
  english_name=excluded.english_name,
  direction=excluded.direction,
  locale=excluded.locale,
  sort_order=excluded.sort_order,
  updated_at=now();

alter table public.localization_languages enable row level security;
alter table public.localization_keys enable row level security;
alter table public.localization_values enable row level security;
alter table public.localization_queue enable row level security;
alter table public.localization_history enable row level security;

revoke all on public.localization_languages from anon;
revoke all on public.localization_keys from anon;
revoke all on public.localization_values from anon;
revoke all on public.localization_queue from anon;
revoke all on public.localization_history from anon;
revoke all on public.localization_approved_values from anon;

grant select on public.localization_languages to authenticated;
grant select on public.localization_approved_values to authenticated;

drop policy if exists "Authenticated users can read enabled localization languages" on public.localization_languages;
create policy "Authenticated users can read enabled localization languages"
on public.localization_languages for select to authenticated
using (is_enabled = true);

drop policy if exists "Authenticated users can read active localization keys" on public.localization_keys;
create policy "Authenticated users can read active localization keys"
on public.localization_keys for select to authenticated
using (is_active = true);

drop policy if exists "Authenticated users can read approved localization values" on public.localization_values;
create policy "Authenticated users can read approved localization values"
on public.localization_values for select to authenticated
using (status = 'approved');

comment on table public.localization_languages is 'Languages available to PETATOE Enterprise Localization Center.';
comment on table public.localization_keys is 'Stable UI translation keys, independent from business data.';
comment on table public.localization_values is 'Reviewed translations by language.';
comment on table public.localization_queue is 'New or missing UI text awaiting review.';
comment on table public.localization_history is 'Audit history for translation changes.';

commit;
