/* PETATOE v9 ELC Phase 4A - Read-only Localization Center dashboard */
(function(){
  'use strict';
  if(window.__PETATOE_ELC_DASHBOARD__) return;
  window.__PETATOE_ELC_DASHBOARD__=true;

  var state={loading:false,loaded:false,error:null,stats:null,rows:[],query:'',language:'all',status:'all',page:1,pageSize:50,total:0};
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function db(){return window.PETATOE_SUPABASE_CLIENT||window.supabase||null}
  function t(key,fallback){try{return window.PETATOE_I18N&&window.PETATOE_I18N.t?window.PETATOE_I18N.t(key,fallback):fallback}catch(_){return fallback}}
  function percent(a,b){return b?Math.round((Number(a||0)/Number(b))*1000)/10:0}
  function statusClass(status){return status==='approved'?'ok':status==='pending'?'warn':status==='rejected'?'bad':'info'}
  function shell(){
    return '<section class="elc-dashboard" data-elc-dashboard>'+
      '<header class="elc-head"><div><h2>🌍 '+esc(t('elc.title','مركز الترجمة'))+'</h2><p>'+esc(t('elc.subtitle','عرض حالة اللغات والترجمات المعتمدة والناقصة — للقراءة فقط.'))+'</p></div><button type="button" class="pet-v110-btn blue" data-elc-action="refresh">↻ '+esc(t('common.refresh','تحديث'))+'</button></header>'+
      '<div class="elc-kpis" data-elc-kpis><div class="elc-skeleton"></div><div class="elc-skeleton"></div><div class="elc-skeleton"></div><div class="elc-skeleton"></div></div>'+
      '<div class="elc-card"><div class="elc-card-head"><h3>'+esc(t('elc.languages','اللغات'))+'</h3><span class="elc-readonly">🔒 '+esc(t('elc.readOnly','وضع القراءة فقط'))+'</span></div><div class="elc-language-grid" data-elc-languages></div></div>'+
      '<div class="elc-card"><div class="elc-card-head"><h3>'+esc(t('elc.translationExplorer','مستكشف الترجمات'))+'</h3><span data-elc-count></span></div><div class="elc-filters">'+
        '<input type="search" data-elc-search placeholder="'+esc(t('elc.searchPlaceholder','ابحث بالمفتاح أو النص...'))+'">'+
        '<select data-elc-language><option value="all">'+esc(t('elc.allLanguages','كل اللغات'))+'</option></select>'+
        '<select data-elc-status><option value="all">'+esc(t('elc.allStatuses','كل الحالات'))+'</option><option value="approved">'+esc(t('elc.approved','معتمد'))+'</option><option value="missing">'+esc(t('elc.missing','ناقص'))+'</option><option value="pending">'+esc(t('elc.pending','قيد المراجعة'))+'</option></select>'+
        '<button type="button" class="pet-v110-btn" data-elc-action="search">'+esc(t('common.search','بحث'))+'</button></div>'+ 
        '<div class="elc-table-wrap"><table class="elc-table"><thead><tr><th>'+esc(t('elc.key','المفتاح'))+'</th><th>'+esc(t('elc.module','الوحدة'))+'</th><th>'+esc(t('elc.language','اللغة'))+'</th><th>'+esc(t('elc.translation','الترجمة'))+'</th><th>'+esc(t('elc.status','الحالة'))+'</th></tr></thead><tbody data-elc-rows><tr><td colspan="5" class="elc-empty">'+esc(t('common.loading','جاري التحميل...'))+'</td></tr></tbody></table></div>'+ 
        '<div class="elc-pager"><button type="button" data-elc-action="prev">‹</button><span data-elc-page>1</span><button type="button" data-elc-action="next">›</button></div></div>'+ 
      '<div class="elc-error" data-elc-error hidden></div></section>';
  }
  function card(label,value,note){return '<article class="elc-kpi"><span>'+esc(label)+'</span><strong>'+esc(value)+'</strong><small>'+esc(note||'')+'</small></article>'}
  function renderStats(root){var s=state.stats||{},langs=s.languages||[];var enabled=langs.filter(function(x){return x.is_enabled}).length;root.querySelector('[data-elc-kpis]').innerHTML=card(t('elc.totalKeys','إجمالي المفاتيح'),s.total_keys||0,t('elc.systemDictionary','قاموس النظام'))+card(t('elc.enabledLanguages','اللغات المفعلة'),enabled,langs.length+' '+t('elc.registered','مسجلة'))+card(t('elc.approvedValues','الترجمات المعتمدة'),s.approved_values||0,t('elc.readyForRuntime','جاهزة للتشغيل'))+card(t('elc.pendingQueue','قائمة الانتظار'),s.pending_queue||0,t('elc.needsReview','تحتاج مراجعة'));
    var select=root.querySelector('[data-elc-language]');select.innerHTML='<option value="all">'+esc(t('elc.allLanguages','كل اللغات'))+'</option>'+langs.map(function(l){return '<option value="'+esc(l.code)+'">'+esc(l.name)+' ('+esc(l.code)+')</option>'}).join('');select.value=state.language;
    root.querySelector('[data-elc-languages]').innerHTML=langs.map(function(l){var approved=Number(l.approved_count||0),total=Number(s.total_keys||0),pc=percent(approved,total);return '<article class="elc-language"><div class="elc-language-title"><span>'+esc(l.name)+'</span><code>'+esc(l.code)+'</code></div><div class="elc-progress"><i style="width:'+pc+'%"></i></div><div class="elc-language-meta"><b>'+pc+'%</b><span>'+approved+' / '+total+'</span><span class="elc-pill '+(l.is_enabled?'ok':'info')+'">'+esc(l.is_enabled?t('elc.enabled','مفعلة'):t('elc.disabled','غير مفعلة'))+'</span></div></article>'}).join('')||'<div class="elc-empty">'+esc(t('elc.noLanguages','لا توجد لغات'))+'</div>';
  }
  function renderRows(root){var rows=state.rows||[];root.querySelector('[data-elc-count]').textContent=state.total+' '+t('elc.results','نتيجة');root.querySelector('[data-elc-page]').textContent=String(state.page);root.querySelector('[data-elc-rows]').innerHTML=rows.length?rows.map(function(r){return '<tr><td><code>'+esc(r.translation_key)+'</code></td><td>'+esc(r.module||'global')+'</td><td><span class="elc-lang-code">'+esc(r.language_code||'—')+'</span></td><td class="elc-text">'+esc(r.translated_text||r.source_text||'—')+'</td><td><span class="elc-pill '+statusClass(r.status)+'">'+esc(r.status||'missing')+'</span></td></tr>'}).join(''):'<tr><td colspan="5" class="elc-empty">'+esc(t('elc.noResults','لا توجد نتائج مطابقة'))+'</td></tr>';
  }
  function showError(root,msg){var el=root.querySelector('[data-elc-error]');el.hidden=!msg;el.textContent=msg||''}
  async function loadStats(root){var c=db();if(!c||typeof c.rpc!=='function')throw new Error(t('elc.supabaseUnavailable','عميل Supabase غير متاح'));var result=await c.rpc('get_localization_dashboard');if(result.error)throw result.error;state.stats=Array.isArray(result.data)?result.data[0]:result.data;renderStats(root)}
  async function loadRows(root){var c=db(),offset=(state.page-1)*state.pageSize;var result=await c.rpc('search_localization_entries',{p_query:state.query||null,p_language_code:state.language==='all'?null:state.language,p_status:state.status==='all'?null:state.status,p_limit:state.pageSize,p_offset:offset});if(result.error)throw result.error;var payload=Array.isArray(result.data)&&result.data.length===1&&result.data[0]&&result.data[0].rows?result.data[0]:null;if(payload){state.rows=payload.rows||[];state.total=Number(payload.total||0)}else{state.rows=Array.isArray(result.data)?result.data:[];state.total=state.rows.length}renderRows(root)}
  async function refresh(root){if(state.loading)return;state.loading=true;showError(root,'');try{await Promise.all([loadStats(root),loadRows(root)]);state.loaded=true}catch(e){state.error=e&&e.message?e.message:String(e);showError(root,t('elc.loadFailed','تعذر تحميل بيانات مركز الترجمة')+': '+state.error)}finally{state.loading=false}}
  function bind(root){if(root.__elcBound)return;root.__elcBound=true;root.addEventListener('click',function(e){var b=e.target.closest('[data-elc-action]');if(!b)return;var a=b.getAttribute('data-elc-action');if(a==='refresh'||a==='search'){state.query=(root.querySelector('[data-elc-search]').value||'').trim();state.language=root.querySelector('[data-elc-language]').value;state.status=root.querySelector('[data-elc-status]').value;state.page=1;refresh(root)}else if(a==='prev'&&state.page>1){state.page--;loadRows(root)}else if(a==='next'&&state.page*state.pageSize<state.total){state.page++;loadRows(root)}});root.querySelector('[data-elc-search]').addEventListener('keydown',function(e){if(e.key==='Enter')root.querySelector('[data-elc-action="search"]').click()})}
  function mount(container){if(!container)return;container.innerHTML=shell();var root=container.querySelector('[data-elc-dashboard]');bind(root);refresh(root);return root}
  window.PETATOELocalizationDashboard={version:'9.0.0-elc-phase4a',mount:mount,refresh:function(){var r=document.querySelector('[data-elc-dashboard]');return r?refresh(r):null},state:state};
})();
