/* PETATOE v9 ELC Phase 4B - Localization Center edit and approval workflow */
(function(){
  'use strict';
  if(window.__PETATOE_ELC_DASHBOARD_PHASE4B__) return;
  window.__PETATOE_ELC_DASHBOARD_PHASE4B__=true;

  var state={loading:false,loaded:false,error:null,stats:null,rows:[],query:'',language:'all',status:'all',page:1,pageSize:50,total:0,editor:null,saving:false};
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function db(){return window.PETATOE_SUPABASE_CLIENT||window.supabase||null}
  function currentUser(){
    try{if(window.PETATOEAuth&&typeof window.PETATOEAuth.currentUser==='function'){var u=window.PETATOEAuth.currentUser();if(u&&typeof u==='object')return u}}catch(_e){}
    try{if(window.__PETATOE_SETTINGS_API__&&typeof window.__PETATOE_SETTINGS_API__.currentUser==='function'){var s=window.__PETATOE_SETTINGS_API__.currentUser();if(s&&typeof s==='object')return s}}catch(_e){}
    try{if(window.currentUser&&typeof window.currentUser==='object')return window.currentUser}catch(_e){}
    return {};
  }
  function authParams(){
    var u=currentUser(),token='';
    try{token=String(sessionStorage.getItem('petatoe_enterprise_session_token_v90')||'').trim()}catch(_e){}
    return {p_actor_user_id:String(u.supabase_id||u.row_id||u.auth_user_id||u.user_id||u.userId||u.id||u.username||'').trim()||null,p_session_token:token||null};
  }
  function withAuth(params){return Object.assign({},params||{},authParams())}
  function t(key,fallback){try{return window.PETATOE_I18N&&window.PETATOE_I18N.t?window.PETATOE_I18N.t(key,fallback):fallback}catch(_){return fallback}}
  function percent(a,b){return b?Math.round((Number(a||0)/Number(b))*1000)/10:0}
  function statusClass(status){return status==='approved'?'ok':status==='pending'?'warn':status==='rejected'?'bad':status==='draft'?'draft':'info'}
  function canEdit(){return !!(state.stats&&state.stats.can_edit)}
  function canApprove(){return !!(state.stats&&state.stats.can_approve)}
  function shell(){
    return '<section class="elc-dashboard" data-elc-dashboard>'+ 
      '<header class="elc-head"><div><h2>🌍 '+esc(t('elc.title','مركز الترجمة'))+'</h2><p>'+esc(t('elc.subtitleManage','إدارة الترجمات ومراجعتها واعتمادها مع سجل كامل للتغييرات.'))+'</p></div><button type="button" class="pet-v110-btn blue" data-elc-action="refresh">↻ '+esc(t('common.refresh','تحديث'))+'</button></header>'+ 
      '<div class="elc-kpis" data-elc-kpis><div class="elc-skeleton"></div><div class="elc-skeleton"></div><div class="elc-skeleton"></div><div class="elc-skeleton"></div></div>'+ 
      '<div class="elc-card"><div class="elc-card-head"><h3>'+esc(t('elc.languages','اللغات'))+'</h3><span class="elc-access" data-elc-access></span></div><div class="elc-language-grid" data-elc-languages></div></div>'+ 
      '<div class="elc-card"><div class="elc-card-head"><h3>'+esc(t('elc.translationExplorer','مستكشف الترجمات'))+'</h3><span data-elc-count></span></div><div class="elc-filters">'+
        '<input type="search" data-elc-search placeholder="'+esc(t('elc.searchPlaceholder','ابحث بالمفتاح أو النص...'))+'">'+
        '<select data-elc-language><option value="all">'+esc(t('elc.allLanguages','كل اللغات'))+'</option></select>'+ 
        '<select data-elc-status><option value="all">'+esc(t('elc.allStatuses','كل الحالات'))+'</option><option value="approved">'+esc(t('elc.approved','معتمد'))+'</option><option value="draft">'+esc(t('elc.draft','مسودة'))+'</option><option value="pending">'+esc(t('elc.pending','قيد المراجعة'))+'</option><option value="rejected">'+esc(t('elc.rejected','مرفوض'))+'</option><option value="missing">'+esc(t('elc.missing','ناقص'))+'</option></select>'+ 
        '<button type="button" class="pet-v110-btn" data-elc-action="search">'+esc(t('common.search','بحث'))+'</button></div>'+ 
        '<div class="elc-table-wrap"><table class="elc-table"><thead><tr><th>'+esc(t('elc.key','المفتاح'))+'</th><th>'+esc(t('elc.module','الوحدة'))+'</th><th>'+esc(t('elc.language','اللغة'))+'</th><th>'+esc(t('elc.translation','الترجمة'))+'</th><th>'+esc(t('elc.status','الحالة'))+'</th><th>'+esc(t('elc.actions','الإجراءات'))+'</th></tr></thead><tbody data-elc-rows><tr><td colspan="6" class="elc-empty">'+esc(t('common.loading','جاري التحميل...'))+'</td></tr></tbody></table></div>'+ 
        '<div class="elc-pager"><button type="button" data-elc-action="prev">‹</button><span data-elc-page>1</span><button type="button" data-elc-action="next">›</button></div></div>'+ 
      '<div class="elc-error" data-elc-error hidden></div>'+editorShell()+'</section>';
  }
  function editorShell(){return '<div class="elc-modal" data-elc-modal hidden><div class="elc-modal-backdrop" data-elc-action="close-editor"></div><section class="elc-modal-panel" role="dialog" aria-modal="true"><header><div><h3 data-elc-editor-title>'+esc(t('elc.editTranslation','تعديل الترجمة'))+'</h3><code data-elc-editor-key></code></div><button type="button" class="elc-close" data-elc-action="close-editor">×</button></header><div class="elc-editor-meta" data-elc-editor-meta></div><label>'+esc(t('elc.sourceText','النص المصدر'))+'<textarea data-elc-source readonly></textarea></label><label>'+esc(t('elc.translation','الترجمة'))+'<textarea data-elc-value maxlength="12000"></textarea></label><label class="elc-reject-reason" data-elc-reject-wrap hidden>'+esc(t('elc.rejectionReason','سبب الرفض'))+'<input type="text" data-elc-reject-reason maxlength="500"></label><div class="elc-editor-actions"><button type="button" class="pet-v110-btn" data-elc-action="save-draft">'+esc(t('elc.saveDraft','حفظ كمسودة'))+'</button><button type="button" class="pet-v110-btn blue" data-elc-action="submit-review">'+esc(t('elc.submitReview','إرسال للمراجعة'))+'</button><button type="button" class="pet-v110-btn green" data-elc-action="approve">'+esc(t('elc.approve','اعتماد'))+'</button><button type="button" class="pet-v110-btn danger" data-elc-action="reject">'+esc(t('elc.reject','رفض'))+'</button></div><div class="elc-history"><h4>'+esc(t('elc.history','سجل التغييرات'))+'</h4><div data-elc-history></div></div><div class="elc-editor-error" data-elc-editor-error hidden></div></section></div>'}
  function card(label,value,note){return '<article class="elc-kpi"><span>'+esc(label)+'</span><strong>'+esc(value)+'</strong><small>'+esc(note||'')+'</small></article>'}
  function renderStats(root){var s=state.stats||{},langs=s.languages||[];var enabled=langs.filter(function(x){return x.is_enabled}).length;root.querySelector('[data-elc-kpis]').innerHTML=card(t('elc.totalKeys','إجمالي المفاتيح'),s.total_keys||0,t('elc.systemDictionary','قاموس النظام'))+card(t('elc.enabledLanguages','اللغات المفعلة'),enabled,langs.length+' '+t('elc.registered','مسجلة'))+card(t('elc.approvedValues','الترجمات المعتمدة'),s.approved_values||0,t('elc.readyForRuntime','جاهزة للتشغيل'))+card(t('elc.pendingQueue','قائمة الانتظار'),s.pending_queue||0,t('elc.needsReview','تحتاج مراجعة'));
    root.querySelector('[data-elc-access]').textContent=(canApprove()?'🔐 '+t('elc.superAdminAccess','صلاحية اعتماد كاملة'):(canEdit()?'✏️ '+t('elc.editorAccess','صلاحية تحرير ومراجعة'):'🔒 '+t('elc.readOnly','وضع القراءة فقط')));
    var select=root.querySelector('[data-elc-language]');select.innerHTML='<option value="all">'+esc(t('elc.allLanguages','كل اللغات'))+'</option>'+langs.map(function(l){return '<option value="'+esc(l.code)+'">'+esc(l.name)+' ('+esc(l.code)+')</option>'}).join('');select.value=state.language;
    root.querySelector('[data-elc-languages]').innerHTML=langs.map(function(l){var approved=Number(l.approved_count||0),total=Number(s.total_keys||0),pc=percent(approved,total);return '<article class="elc-language"><div class="elc-language-title"><span>'+esc(l.name)+'</span><code>'+esc(l.code)+'</code></div><div class="elc-progress"><i style="width:'+pc+'%"></i></div><div class="elc-language-meta"><b>'+pc+'%</b><span>'+approved+' / '+total+'</span><span class="elc-pill '+(l.is_enabled?'ok':'info')+'">'+esc(l.is_enabled?t('elc.enabled','مفعلة'):t('elc.disabled','غير مفعلة'))+'</span></div></article>'}).join('')||'<div class="elc-empty">'+esc(t('elc.noLanguages','لا توجد لغات'))+'</div>';
  }
  function actionButtons(r){if(!canEdit())return '—';return '<button type="button" class="elc-row-action" data-elc-action="edit" data-key="'+esc(r.translation_key)+'" data-language="'+esc(r.language_code)+'">'+esc(t('elc.open','فتح'))+'</button>'}
  function renderRows(root){var rows=state.rows||[];root.querySelector('[data-elc-count]').textContent=state.total+' '+t('elc.results','نتيجة');root.querySelector('[data-elc-page]').textContent=String(state.page);root.querySelector('[data-elc-rows]').innerHTML=rows.length?rows.map(function(r){return '<tr><td><code>'+esc(r.translation_key)+'</code></td><td>'+esc(r.module||'global')+'</td><td><span class="elc-lang-code">'+esc(r.language_code||'—')+'</span></td><td class="elc-text">'+esc(r.translated_text||r.suggested_text||r.source_text||'—')+'</td><td><span class="elc-pill '+statusClass(r.status)+'">'+esc(t('elc.status_'+(r.status||'missing'),r.status||'missing'))+'</span></td><td>'+actionButtons(r)+'</td></tr>'}).join(''):'<tr><td colspan="6" class="elc-empty">'+esc(t('elc.noResults','لا توجد نتائج مطابقة'))+'</td></tr>'}
  function showError(root,msg){var el=root.querySelector('[data-elc-error]');el.hidden=!msg;el.textContent=msg||''}
  function editorError(root,msg){var el=root.querySelector('[data-elc-editor-error]');el.hidden=!msg;el.textContent=msg||''}
  async function loadStats(root){var c=db();if(!c||typeof c.rpc!=='function')throw new Error(t('elc.supabaseUnavailable','عميل Supabase غير متاح'));var result=await c.rpc('get_localization_dashboard',withAuth());if(result.error)throw result.error;state.stats=Array.isArray(result.data)?result.data[0]:result.data;renderStats(root)}
  async function loadRows(root){var c=db(),offset=(state.page-1)*state.pageSize;var result=await c.rpc('search_localization_entries',withAuth({p_query:state.query||null,p_language_code:state.language==='all'?null:state.language,p_status:state.status==='all'?null:state.status,p_limit:state.pageSize,p_offset:offset}));if(result.error)throw result.error;var payload=Array.isArray(result.data)&&result.data.length===1&&result.data[0]&&result.data[0].rows?result.data[0]:result.data;if(payload&&payload.rows){state.rows=payload.rows||[];state.total=Number(payload.total||0)}else{state.rows=Array.isArray(payload)?payload:[];state.total=state.rows.length}renderRows(root)}
  async function refresh(root){if(state.loading)return;state.loading=true;showError(root,'');try{await Promise.all([loadStats(root),loadRows(root)]);state.loaded=true}catch(e){state.error=e&&e.message?e.message:String(e);showError(root,t('elc.loadFailed','تعذر تحميل بيانات مركز الترجمة')+': '+state.error)}finally{state.loading=false}}
  function historyHtml(items){return (items&&items.length)?items.map(function(h){return '<article><div><b>'+esc(h.action||'')+'</b><time>'+esc(new Date(h.changed_at).toLocaleString())+'</time></div><p>'+esc(h.old_text||'—')+' → '+esc(h.new_text||'—')+'</p></article>'}).join(''):'<div class="elc-empty">'+esc(t('elc.noHistory','لا يوجد سجل تغييرات'))+'</div>'}
  async function openEditor(root,key,language){editorError(root,'');var c=db(),res=await c.rpc('get_localization_entry',withAuth({p_translation_key:key,p_language_code:language}));if(res.error)throw res.error;state.editor=Array.isArray(res.data)?res.data[0]:res.data;var e=state.editor||{};root.querySelector('[data-elc-editor-key]').textContent=e.translation_key||key;root.querySelector('[data-elc-editor-title]').textContent=t('elc.editTranslation','تعديل الترجمة')+' — '+(e.language_name||language);root.querySelector('[data-elc-editor-meta]').innerHTML='<span>'+esc(t('elc.module','الوحدة'))+': <b>'+esc(e.module||'global')+'</b></span><span>'+esc(t('elc.status','الحالة'))+': <b class="elc-pill '+statusClass(e.status)+'">'+esc(t('elc.status_'+(e.status||'missing'),e.status||'missing'))+'</b></span><span>'+esc(t('elc.version','الإصدار'))+': <b>'+esc(e.version||0)+'</b></span>';root.querySelector('[data-elc-source]').value=e.source_text||'';root.querySelector('[data-elc-value]').value=e.translated_text||e.suggested_text||'';root.querySelector('[data-elc-history]').innerHTML=historyHtml(e.history||[]);root.querySelector('[data-elc-action="approve"]').hidden=!canApprove();root.querySelector('[data-elc-action="reject"]').hidden=!canApprove();root.querySelector('[data-elc-reject-wrap]').hidden=true;root.querySelector('[data-elc-modal]').hidden=false;setTimeout(function(){root.querySelector('[data-elc-value]').focus()},20)}
  function closeEditor(root){root.querySelector('[data-elc-modal]').hidden=true;state.editor=null;editorError(root,'')}
  async function saveEditor(root,mode){if(state.saving||!state.editor)return;var text=(root.querySelector('[data-elc-value]').value||'').trim();if(!text&&mode!=='reject'){editorError(root,t('elc.translationRequired','الترجمة مطلوبة'));return}state.saving=true;editorError(root,'');try{var c=db(),params={p_translation_key:state.editor.translation_key,p_language_code:state.editor.language_code},res;if(mode==='draft'||mode==='submit'){params.p_translated_text=text;params.p_submit=mode==='submit';res=await c.rpc('save_localization_draft',withAuth(params))}else if(mode==='approve'){params.p_translated_text=text;res=await c.rpc('approve_localization_value',withAuth(params))}else{var wrap=root.querySelector('[data-elc-reject-wrap]'),reason=(root.querySelector('[data-elc-reject-reason]').value||'').trim();if(wrap.hidden){wrap.hidden=false;root.querySelector('[data-elc-reject-reason]').focus();return}params.p_reason=reason||null;res=await c.rpc('reject_localization_value',withAuth(params))}if(res&&res.error)throw res.error;closeEditor(root);await refresh(root);try{if(window.PETATOELocalizationRuntime&&window.PETATOELocalizationRuntime.reload)window.PETATOELocalizationRuntime.reload()}catch(_){}}catch(e){editorError(root,(e&&e.message)||String(e))}finally{state.saving=false}}
  function bind(root){if(root.__elcBound)return;root.__elcBound=true;root.addEventListener('click',function(e){var b=e.target.closest('[data-elc-action]');if(!b)return;var a=b.getAttribute('data-elc-action');if(a==='refresh'||a==='search'){state.query=(root.querySelector('[data-elc-search]').value||'').trim();state.language=root.querySelector('[data-elc-language]').value;state.status=root.querySelector('[data-elc-status]').value;state.page=1;refresh(root)}else if(a==='prev'&&state.page>1){state.page--;loadRows(root)}else if(a==='next'&&state.page*state.pageSize<state.total){state.page++;loadRows(root)}else if(a==='edit'){openEditor(root,b.getAttribute('data-key'),b.getAttribute('data-language')).catch(function(err){showError(root,(err&&err.message)||String(err))})}else if(a==='close-editor'){closeEditor(root)}else if(a==='save-draft'){saveEditor(root,'draft')}else if(a==='submit-review'){saveEditor(root,'submit')}else if(a==='approve'){saveEditor(root,'approve')}else if(a==='reject'){saveEditor(root,'reject')}});root.querySelector('[data-elc-search]').addEventListener('keydown',function(e){if(e.key==='Enter')root.querySelector('[data-elc-action="search"]').click()});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!root.querySelector('[data-elc-modal]').hidden)closeEditor(root)})}
  function mount(container){if(!container)return;container.innerHTML=shell();var root=container.querySelector('[data-elc-dashboard]');bind(root);refresh(root);return root}
  window.PETATOELocalizationDashboard={version:'9.0.0-elc-phase4b.2',mount:mount,refresh:function(){var r=document.querySelector('[data-elc-dashboard]');return r?refresh(r):null},state:state};
})();
