/* PETATOE v9.4.8 — Phase 6.1 Settings Localization Catalog
 * Canonical Settings translations registered inside PETATOE Localization Center.
 */
(function(){
  'use strict';
  var CATALOG={
    ar:{permissions:{
      screens:{
        dashboardManagement:{title:'Dashboard الإدارة',description:'لوحة المؤشرات المالية والإدارية للإدارة فقط'},
        dashboardOperations:{title:'Dashboard التشغيل',description:'لوحة تشغيل مبسطة للسائقين والجرومرز ومشرفي التشغيل'},
        sales:{title:'فواتير المبيعات',description:'إضافة وتعديل وحذف فواتير البيع اليدوية والمستوردة'},
        customers:{title:'العملاء',description:'بيانات العملاء وتحليلاتهم وسجلاتهم'},services:{title:'الخدمات / الأصناف',description:'أصناف الخدمات وأسعارها وتصنيفاتها'},
        appointments:{title:'إدارة المواعيد',description:'تسجيل ومتابعة مواعيد جلسات العملاء'},vehicleOperations:{title:'تشغيل السيارات',description:'تنفيذ جلسات اليوم والتحصيل وحركة السيارات'},
        vehicleOperationsReports:{title:'تقارير تشغيل السيارات',description:'عرض وتحليل تقارير تشغيل السيارات والتحصيل'},operationKpis:{title:'مؤشرات الأداء التشغيلية',description:'مؤشرات KPI الخاصة بالتشغيل والجودة'},
        vehicles:{title:'السيارات',description:'إدارة السيارات وخزن السيارات والتقارير المرتبطة'},vaults:{title:'الخزن',description:'الخزن الرئيسية والفرعية وخزن السيارات'},
        treasury:{title:'الخزينة',description:'الحركات المالية وكشف الحساب والأرصدة'},expenses:{title:'المصروفات',description:'المصروفات التشغيلية ومراكز التكلفة'},
        obligations:{title:'الالتزامات',description:'الالتزامات الشهرية والسداد والحذف'},commissions:{title:'العمولات',description:'الشرائح واحتساب العمولات والأرشيف'},
        commissionStatement:{title:'كشف العمولة',description:'عرض كشف العمولة الخاص بالمستخدم فقط'},payroll:{title:'إدارة الرواتب',description:'إدارة الموظفين وكشوف الرواتب واعتمادات الصرف'},
        salarySlip:{title:'كشف الراتب',description:'عرض كشف الراتب الخاص بالموظف فقط'},childrenExpenses:{title:'مصروفات الأبناء',description:'متابعة مصروفات الأبناء حسب صلاحية المستخدم'},
        reports:{title:'التقارير والتحليلات',description:'التقارير الذكية والتحليلات ومركز الأعمال'},settings:{title:'الإعدادات العامة',description:'إعدادات النظام والعملة والهدف واللغة'},
        setup:{title:'التهيئة / البيانات المرجعية',description:'الخدمات والسيارات والعملاء والخزن داخل Master Data'},users:{title:'المستخدمين',description:'إضافة وتعديل وحذف المستخدمين'},
        permissions:{title:'الصلاحيات',description:'منح أو تعديل صلاحيات المستخدمين'},audit:{title:'السجل النظامي',description:'عرض وتصدير ومسح سجل النشاط'}
      },
      actions:{view:'عرض',add:'إضافة',edit:'تعديل',delete:'حذف'},
      specials:{
        export_pdf:'تصدير PDF',export_excel:'تصدير Excel',backup:'نسخ احتياطي',restore:'استعادة البيانات',manage_users:'إدارة المستخدمين',manage_permissions:'إدارة الصلاحيات',hard_delete:'حذف نهائي',edit_closed:'تعديل بعد الإغلاق',view_profit:'عرض الأرباح',edit_targets:'تعديل الأهداف',manage_security:'إدارة الأمان',data_quality:'فحص البيانات',payroll_cancel_approval:'إلغاء اعتماد الرواتب',children_expenses_budget:'مصروفات الأبناء - إدارة الميزانية',children_expenses_export:'مصروفات الأبناء - تصدير/طباعة التقارير',operations_close_session:'تشغيل السيارات - إغلاق جلسة',operations_reopen_session:'تشغيل السيارات - إعادة فتح جلسة',operations_confirm_session:'تشغيل السيارات - تأكيد جلسة',operations_edit_confirmed_session:'تشغيل السيارات - تعديل جلسة مؤكدة',vehicle_ops_create_trip:'تشغيل السيارات - إنشاء رحلة',vehicle_ops_edit_trip:'تشغيل السيارات - تعديل رحلة/تحصيل',vehicle_ops_cancel_trip:'تشغيل السيارات - إلغاء رحلة',vehicle_ops_reopen_trip:'تشغيل السيارات - فتح مرة أخرى',vehicle_ops_approve_trip:'تشغيل السيارات - اعتماد الرحلة',vehicle_ops_print:'تقارير تشغيل السيارات - طباعة',vehicle_ops_export:'تقارير تشغيل السيارات - تصدير',vehicle_ops_export_excel:'تقارير تشغيل السيارات - تصدير Excel',vehicle_ops_export_pdf:'تقارير تشغيل السيارات - تصدير PDF',vehicle_ops_view_reports:'تقارير تشغيل السيارات - عرض',vehicle_ops_view_kpis:'مؤشرات التشغيل - عرض',treasury_tab_home:'الخزينة - الواجهة الرئيسية',treasury_tab_balances:'الخزينة - الأرصدة',treasury_tab_movements:'الخزينة - التسليمات',treasury_tab_expenses:'الخزينة - المصروفات',treasury_tab_statement:'الخزينة - كشف الحساب',treasury_tab_log:'الخزينة - سجل الحركات',treasury_tab_audit:'الخزينة - سجل التدقيق',treasury_tab_reports:'الخزينة - التقارير'
      },
      modules:{
        home:{title:'الرئيسية',hint:'فصل Dashboard الإدارة عن Dashboard التشغيل'},operations:{title:'إدارة التشغيل',hint:'تشغيل السيارات منفصل عن تقارير التشغيل ومؤشرات الأداء'},salary:{title:'الرواتب والعمولات',hint:'صلاحيات الموظف الشخصية منفصلة عن إدارة الرواتب'},sales:{title:'المبيعات والعملاء',hint:'الفواتير والعملاء والخدمات والتقارير العامة'},finance:{title:'الخزنة والحسابات',hint:'الخزن والحركات المالية والمصروفات والالتزامات'},fleet:{title:'السيارات والمخازن',hint:'إدارة السيارات وربط التشغيل بالسيارات'},children:{title:'مصروفات الأبناء',hint:'مصروفات الأبناء وميزانيتها وتقاريرها'},admin:{title:'الإدارة والإعدادات',hint:'إدارة المستخدمين والصلاحيات والتهيئة والأمان'}
      },
      common:{screensCount:'شاشات',screenFunction:'الشاشة / الوظيفة',extraPermissionsIn:'صلاحيات إضافية داخل'},
      vehicleScope:{title:'ربط تشغيل السيارات بالسيارات',description:'تحديد السيارات المسموح للمستخدم بتشغيلها أو عرض تقاريرها.',allVehicles:'كل السيارات الحالية والمستقبلية',noVehicles:'لا توجد سيارات مسجلة حاليًا. يمكن إضافة السيارات من شاشة التهيئة أو إدارة السيارات.'},
      hero:{title:'إدارة الصلاحيات',description:'تنظيم ERP واضح: القسم ← الشاشة ← عرض / إضافة / تعديل / حذف. يتم عرض القسم المحدد فقط لضمان عدم تداخل الصلاحيات.',superAdminFull:'Super Admin كامل الصلاحيات',currentSection:'القسم الحالي: {section}'},
      controls:{user:'المستخدم',selectedUser:'المستخدم المحدد',username:'اسم الدخول',currentRole:'الدور الحالي',saveChanges:'حفظ التغييرات',viewOnly:'عرض فقط',driverGroomerTemplate:'قالب سائق/جرومر',operationalTemplate:'قالب تشغيلي',restoreDefault:'إرجاع الافتراضي',superAdminWarning:'هذا المستخدم Super Admin، صلاحياته كاملة ومحميّة ولا يمكن تعطيلها من هذه الشاشة.'},
      help:{otherPermissionsTitle:'صلاحيات عامة أخرى',otherPermissionsDescription:'صلاحيات عامة غير مرتبطة بشاشة واحدة.',infoTitle:'معلومات',infoDescription:'اختر القسم من الأعلى. مربع الاختيار في رأس العمود يحدد أو يلغي كل صلاحيات هذا العمود داخل القسم الحالي فقط.',templatesTitle:'قوالب أساسية',driverGroomer:'Driver/Groomer: Dashboard التشغيل + كشف الراتب + كشف العمولة + تشغيل السيارات فقط.',operations:'Operations: تشغيل السيارات وتقارير التشغيل.',accountant:'Accountant: المبيعات والخزنة والرواتب.',superAdmin:'Super Admin: كل الصلاحيات.'},messages:{selectUserFirst:'اختر مستخدم أولاً',superAdminProtected:'Super Admin كامل الصلاحيات ومحمي',saveFailed:'فشل حفظ الصلاحيات: {error}',saved:'تم حفظ صلاحيات المستخدم',readOnlyPrepared:'تم تجهيز صلاحية العرض فقط للقسم الحالي، اضغط حفظ للتأكيد',driverTemplateFailed:'فشل تطبيق قالب السائق/الجرومر: {error}',driverTemplateApplied:'تم تطبيق قالب السائق/الجرومر',operationalTemplateFailed:'فشل تطبيق القالب التشغيلي: {error}',operationalTemplateApplied:'تم تطبيق القالب التشغيلي',confirmRestoreDefault:'إرجاع صلاحيات هذا المستخدم للوضع الافتراضي؟',restoredDefault:'تم إرجاع صلاحيات المستخدم'}
    }},
    en:{permissions:{
      screens:{
        dashboardManagement:{title:'Management Dashboard',description:'Financial and administrative indicators for management only'},dashboardOperations:{title:'Operations Dashboard',description:'Simplified operations dashboard for drivers, groomers, and supervisors'},sales:{title:'Sales Invoices',description:'Create, edit, and delete manual and imported sales invoices'},customers:{title:'Customers',description:'Customer data, analytics, and records'},services:{title:'Services / Items',description:'Service items, prices, and categories'},appointments:{title:'Appointment Management',description:'Create and track customer session appointments'},vehicleOperations:{title:'Vehicle Operations',description:'Execute today’s sessions, collections, and vehicle movement'},vehicleOperationsReports:{title:'Vehicle Operations Reports',description:'View and analyze vehicle operations and collection reports'},operationKpis:{title:'Operations KPIs',description:'Operations and quality KPI indicators'},vehicles:{title:'Vehicles',description:'Manage vehicles, vehicle vaults, and related reports'},vaults:{title:'Vaults',description:'Main, sub, and vehicle vaults'},treasury:{title:'Treasury',description:'Financial movements, statements, and balances'},expenses:{title:'Expenses',description:'Operating expenses and cost centers'},obligations:{title:'Obligations',description:'Monthly obligations, payment, and deletion'},commissions:{title:'Commissions',description:'Tiers, commission calculation, and archive'},commissionStatement:{title:'Commission Statement',description:'View only the current user’s commission statement'},payroll:{title:'Payroll Management',description:'Manage employees, payroll statements, and payment approvals'},salarySlip:{title:'Salary Slip',description:'View only the employee’s salary slip'},childrenExpenses:{title:'Children Expenses',description:'Track children expenses according to user permissions'},reports:{title:'Reports & Analytics',description:'Smart reports, analytics, and business center'},settings:{title:'General Settings',description:'System, currency, target, and language settings'},setup:{title:'Setup / Master Data',description:'Services, vehicles, customers, and vaults in Master Data'},users:{title:'Users',description:'Create, edit, and delete users'},permissions:{title:'Permissions',description:'Grant or modify user permissions'},audit:{title:'Audit Trail',description:'View, export, and clear the activity log'}
      },
      actions:{view:'View',add:'Add',edit:'Edit',delete:'Delete'},
      specials:{export_pdf:'Export PDF',export_excel:'Export Excel',backup:'Backup',restore:'Restore Data',manage_users:'Manage Users',manage_permissions:'Manage Permissions',hard_delete:'Permanent Delete',edit_closed:'Edit After Closing',view_profit:'View Profit',edit_targets:'Edit Targets',manage_security:'Manage Security',data_quality:'Data Quality Check',payroll_cancel_approval:'Cancel Payroll Approval',children_expenses_budget:'Children Expenses - Manage Budget',children_expenses_export:'Children Expenses - Export/Print Reports',operations_close_session:'Vehicle Operations - Close Session',operations_reopen_session:'Vehicle Operations - Reopen Session',operations_confirm_session:'Vehicle Operations - Confirm Session',operations_edit_confirmed_session:'Vehicle Operations - Edit Confirmed Session',vehicle_ops_create_trip:'Vehicle Operations - Create Trip',vehicle_ops_edit_trip:'Vehicle Operations - Edit Trip/Collection',vehicle_ops_cancel_trip:'Vehicle Operations - Cancel Trip',vehicle_ops_reopen_trip:'Vehicle Operations - Reopen Trip',vehicle_ops_approve_trip:'Vehicle Operations - Approve Trip',vehicle_ops_print:'Vehicle Operations Reports - Print',vehicle_ops_export:'Vehicle Operations Reports - Export',vehicle_ops_export_excel:'Vehicle Operations Reports - Export Excel',vehicle_ops_export_pdf:'Vehicle Operations Reports - Export PDF',vehicle_ops_view_reports:'Vehicle Operations Reports - View',vehicle_ops_view_kpis:'Operations KPIs - View',treasury_tab_home:'Treasury - Home',treasury_tab_balances:'Treasury - Balances',treasury_tab_movements:'Treasury - Deliveries',treasury_tab_expenses:'Treasury - Expenses',treasury_tab_statement:'Treasury - Statement',treasury_tab_log:'Treasury - Movement Log',treasury_tab_audit:'Treasury - Audit Log',treasury_tab_reports:'Treasury - Reports'},
      modules:{home:{title:'Home',hint:'Separate the management dashboard from the operations dashboard'},operations:{title:'Operations Management',hint:'Separate vehicle operations from operations reports and KPIs'},salary:{title:'Payroll & Commissions',hint:'Personal employee access is separate from payroll management'},sales:{title:'Sales & Customers',hint:'Invoices, customers, services, and general reports'},finance:{title:'Treasury & Accounts',hint:'Vaults, financial movements, expenses, and obligations'},fleet:{title:'Vehicles & Stores',hint:'Vehicle management and vehicle-operation assignment'},children:{title:'Children Expenses',hint:'Children expenses, budgets, and reports'},admin:{title:'Management & Settings',hint:'Users, permissions, setup, and security management'}},
      common:{screensCount:'screens',screenFunction:'Screen / Function',extraPermissionsIn:'Additional permissions in'},vehicleScope:{title:'Vehicle Operation Assignment',description:'Select the vehicles this user may operate or report on.',allVehicles:'All current and future vehicles',noVehicles:'No vehicles are currently registered. Add vehicles from Setup or Vehicle Management.'},hero:{title:'Permissions Management',description:'Clear ERP structure: section ← screen ← view / add / edit / delete. Only the selected section is shown to prevent permission overlap.',superAdminFull:'Super Admin has full permissions',currentSection:'Current section: {section}'},controls:{user:'User',selectedUser:'Selected user',username:'Username',currentRole:'Current role',saveChanges:'Save Changes',viewOnly:'View only',driverGroomerTemplate:'Driver/Groomer Template',operationalTemplate:'Operational Template',restoreDefault:'Restore Default',superAdminWarning:'This user is a protected Super Admin with full permissions and cannot be disabled from this screen.'},help:{otherPermissionsTitle:'Other General Permissions',otherPermissionsDescription:'General permissions not tied to one screen.',infoTitle:'Information',infoDescription:'Choose a section above. The checkbox in a column header selects or clears that permission for the current section only.',templatesTitle:'Base Templates',driverGroomer:'Driver/Groomer: Operations Dashboard + Salary Slip + Commission Statement + Vehicle Operations only.',operations:'Operations: Vehicle operations and operations reports.',accountant:'Accountant: Sales, treasury, and payroll.',superAdmin:'Super Admin: All permissions.'},messages:{selectUserFirst:'Select a user first',superAdminProtected:'Super Admin has full permissions and is protected',saveFailed:'Failed to save permissions: {error}',saved:'User permissions saved',readOnlyPrepared:'View-only permissions are ready for the current section. Click Save to confirm.',driverTemplateFailed:'Failed to apply Driver/Groomer template: {error}',driverTemplateApplied:'Driver/Groomer template applied',operationalTemplateFailed:'Failed to apply operational template: {error}',operationalTemplateApplied:'Operational template applied',confirmRestoreDefault:'Restore this user permissions to the default state?',restoredDefault:'User permissions restored to default'}
    }}
  };
  function register(){
    var s=window.PETATOE_LOCALIZATION_CENTER_STORE;
    if(!s||typeof s.registerModule!=='function')return false;
    s.registerModule('settingsPhase61',CATALOG);
    window.dispatchEvent(new CustomEvent('petatoe:settings-phase61-localization-ready',{detail:{version:'9.4.8',module:'settingsPhase61'}}));
    return true;
  }
  if(!register())window.addEventListener('petatoe:localization-center-store-ready',register,{once:true});
})();
