/* PETATOE v9.4.23 — Settings Backup localization catalog */
(function(){
  'use strict';
  var CATALOG={
    ar:{shell:{description:'إعدادات التشغيل، الصلاحيات، النسخ الاحتياطي، وفحص جودة البيانات.',dataQuality:'🧪 فحص البيانات'},backup:{invalidJson:'ملف JSON غير صالح',unsupportedType:'نوع ملف غير مدعوم',invalidRecords:'صيغة بيانات المبيعات داخل الملف غير صالحة',invalidUsers:'صيغة المستخدمين داخل الملف غير صالحة',invalidRoles:'صيغة الصلاحيات داخل الملف غير صالحة',invalidSystem:'صيغة إعدادات النظام غير صالحة',invalidSecurity:'صيغة إعدادات الأمان غير صالحة',emptyFile:'الملف لا يحتوي بيانات قابلة للاستيراد',title:'💾 Backup',description:'تصدير نسخة JSON من البيانات المحمّلة من Supabase فقط، بدون أي LocalStorage.',exportFull:'تصدير Backup JSON',exportData:'تصدير بيانات المبيعات فقط',restoreTitle:'♻️ Restore',restoreDescription:'استيراد محدود وآمن للبيانات المدعومة فقط. لا يتم استرجاع أي لقطة LocalStorage قديمة.',restoreAction:'استيراد / Restore',restoreHint:'يفضل تصدير Backup قبل أي Restore.',exportedFull:'تم تصدير Backup من بيانات Supabase',exportedData:'تم تصدير البيانات فقط',confirmRestore:'سيتم استيراد ملف JSON للبيانات المدعومة فقط. هل تتابع؟',restoreSuccess:'تم الاستيراد بنجاح',restoreFailed:'تعذر استيراد ملف Backup',fileTooLarge:'حجم ملف Backup أكبر من الحد الآمن'}},
    en:{shell:{description:'Operations settings, permissions, backup, and data quality checks.',dataQuality:'🧪 Data Quality Check'},backup:{invalidJson:'Invalid JSON file',unsupportedType:'Unsupported file type',invalidRecords:'The sales data format in this file is invalid',invalidUsers:'The users format in this file is invalid',invalidRoles:'The permissions format in this file is invalid',invalidSystem:'The system settings format in this file is invalid',invalidSecurity:'The security settings format in this file is invalid',emptyFile:'The file contains no supported data to import',title:'💾 Backup',description:'Export a JSON backup using data loaded from Supabase only, without any LocalStorage snapshot.',exportFull:'Export Backup JSON',exportData:'Export Sales Data Only',restoreTitle:'♻️ Restore',restoreDescription:'Import only supported data through a restricted and safe restore flow. Legacy LocalStorage snapshots are not restored.',restoreAction:'Import / Restore',restoreHint:'Export a backup before running any restore.',exportedFull:'Supabase backup exported successfully',exportedData:'Sales data exported successfully',confirmRestore:'This imports only supported JSON data. Continue?',restoreSuccess:'Import completed successfully',restoreFailed:'Unable to import the backup file',fileTooLarge:'The backup file exceeds the safe size limit'}}
  };
  function register(){var s=window.PETATOE_LOCALIZATION_CENTER_STORE;if(!s||typeof s.registerModule!=='function')return false;s.registerModule('settingsBackup',CATALOG);return true;}
  if(!register())window.addEventListener('petatoe:localization-center-store-ready',register,{once:true});
})();
