/* PETATOE v3.11.38 Phase 4 Cleanup: extracted from index.html. */
(function(){
'use strict';
if(window.__PETATOE_OBLIGATIONS_STABLE_3839__) return;
window.__PETATOE_OBLIGATIONS_STABLE_3839__=true;
var OBL_KEY='petatoe_obligations_v1';
var MOVES_KEY='petatoe_manual_movement_center_v383';
var EMAIL_KEY='petatoe_obligation_email_settings_v1';
var TYPE_LABELS={bills:'فواتير',gov:'رسوم حكومية',annual:'رسوم واشتراكات سنوية'};
var FREQ_LABELS={'1':'شهري','3':'كل 3 شهور','6':'كل 6 شهور','9':'كل 9 شهور','12':'سنوي'};
var STATUS_LABELS={new:'جديد',active:'جديد',paused:'متوقف',deleted:'محذوف',paid:'مسدد'};
/* v3.11.10: using global byId */
function block_6492_esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}

function obSafeHtml(el, html, reason){
  if(!el)return;
  try{
    if(window.PETATOESafeRender && typeof window.PETATOESafeRender.htmlTrusted==='function'){
      window.PETATOESafeRender.htmlTrusted(el, html, reason||'obligations trusted template');
      return;
    }
  }catch(e){try{if(window.PETATOEUtils&&window.PETATOEUtils.warnSilentCatch)window.PETATOEUtils.warnSilentCatch('obligations-core.js safe render',e)}catch(_){try{if(window.PETATOECaptureSilentCatch)window.PETATOECaptureSilentCatch('obligations/obligations-core.js',_,{phase:'v6.5.9-risk-cleanup'});}catch(_petatoeSilentCatch){window.PETATOEUtils&&window.PETATOEUtils.warnSilentCatch&&window.PETATOEUtils.warnSilentCatch('obligations/obligations-core.js',_petatoeSilentCatch);}}}
  (window.PETATOESecurity||{setInnerHTML:function(el,h){el.replaceChildren(document.createRange().createContextualFragment(String(h==null?'':h)));}}).setInnerHTML(el, html);
}
function obligationReplaceOptions(select, items, selectedValue){
  if(!select)return;
  while(select.firstChild)select.removeChild(select.firstChild);
  (items||[]).forEach(function(item){
    var opt=document.createElement('option');
    opt.value=String(item&&item.value!=null?item.value:'');
    opt.textContent=String(item&&item.label!=null?item.label:opt.value);
    select.appendChild(opt);
  });
  if(selectedValue!=null)select.value=String(selectedValue);
}
var OBL_REMOTE_TABLE='operations_master_data';
var OBL_REMOTE_ID='obligations_persistent_store_v1';
var obligationsRemoteCache={};
var obligationsRemoteLoaded=false;
var obligationsRemoteLoading=null;
function obligationsRepo(){return window.PETATOESupabaseRepository||null}
function obligationsDefaultStore(){var o={};o[OBL_KEY]=[];o[MOVES_KEY]=[];o[EMAIL_KEY]={};return o}
function obligationsNotifyStorage(){try{window.dispatchEvent(new CustomEvent('petatoe:obligations-storage-change',{detail:{source:'supabase'}}))}catch(_e){}}
function obligationsLoadRemote(){
  if(obligationsRemoteLoading)return obligationsRemoteLoading;
  var R=obligationsRepo();
  if(!R||typeof R.getSingleton!=='function'){obligationsRemoteLoaded=true;return Promise.resolve(obligationsRemoteCache)}
  obligationsRemoteLoading=R.getSingleton(OBL_REMOTE_TABLE,OBL_REMOTE_ID,obligationsDefaultStore()).then(function(data){
    obligationsRemoteCache=data&&typeof data==='object'?data:obligationsDefaultStore();
    obligationsRemoteLoaded=true; obligationsNotifyStorage(); return obligationsRemoteCache;
  }).catch(function(e){console.warn('PETATOE obligations Supabase load failed',e); obligationsRemoteLoaded=true; return obligationsRemoteCache;});
  return obligationsRemoteLoading;
}
function obligationsSaveRemote(){
  var R=obligationsRepo();
  if(!R||typeof R.saveSingleton!=='function')return Promise.resolve({ok:false,error:'Supabase repository not ready'});
  return R.saveSingleton(OBL_REMOTE_TABLE,OBL_REMOTE_ID,obligationsRemoteCache).catch(function(e){console.warn('PETATOE obligations Supabase save failed',e);return {ok:false,error:String(e&&e.message||e)}});
}
function obligationsReadJson(k,d){if(!obligationsRemoteLoaded)obligationsLoadRemote();return Object.prototype.hasOwnProperty.call(obligationsRemoteCache,k)?obligationsRemoteCache[k]:d}
function obligationsWriteJson(k,v){try{obligationsRemoteCache[k]=v;obligationsRemoteLoaded=true;obligationsSaveRemote();obligationsNotifyStorage();}catch(e){console.warn(e)}}
/* Phase 42.9C: obligations business data is Supabase-backed only. */
function obligationsReadStore(k,d){return obligationsReadJson(k,d)}
function obligationsWriteStore(k,v){return obligationsWriteJson(k,v)}
function arr(){var a=obligationsReadStore(OBL_KEY,[]);return Array.isArray(a)?a:[]}
function save(a){obligationsWriteStore(OBL_KEY,a||[])}
function petBlock6501_today(){return (window.PETATOEDate&&PETATOEDate.todayDate)?PETATOEDate.todayDate():(function(){var d=new Date();d.setHours(0,0,0,0);return d})()}
function iso(d){if(!d||isNaN(d.getTime()))return '';return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function block_6492_parseDate(v){if(!v)return null; var s=String(v).slice(0,10); var d=new Date(s+'T00:00:00'); return isNaN(d.getTime())?null:d}
function daysTo(v){var d=block_6492_parseDate(v); if(!d)return 99999; return Math.ceil((d-petBlock6501_today())/86400000)}
function addMonths(d,m){d=new Date((d||petBlock6501_today()).getTime());var day=d.getDate();d.setMonth(d.getMonth()+Number(m||1));if(d.getDate()<day)d.setDate(0);return d}
function petBlock6501_money(n){n=Number(n||0);return n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})+' SAR'}
function toastMsg(m){try{if(typeof window.toast==='function')window.toast(m);else alert(m)}catch(e){alert(m)}}
function userName(){try{return window.PETATOEDataSource.getCurrentUserName('Admin')}catch(e){return 'Admin'}}
function moves(){var a=obligationsReadStore(MOVES_KEY,[]);return Array.isArray(a)?a:[]}
function addMove(action,o,level,extra){try{var a=moves();a.unshift(Object.assign({id:'mv_'+Date.now()+'_'+Math.random().toString(36).slice(2),time:new Date().toISOString(),user:userName(),type:'obligation',action:action,name:(o&&o.name)||'-',invoice:(o&&o.id)||'-',date:((o&&(o.dueDate||o.updatedAt||o.createdAt))||'').slice(0,10),level:level||'info'},extra||{}));obligationsWriteStore(MOVES_KEY,a.slice(0,3000))}catch(e){console.warn(e)}}
function obligationStatusNorm(o){if(!o)return 'new'; if(o.active===false||o.status==='deleted')return 'deleted'; if(o.status==='paused'||o.paused===true)return 'paused'; if(o.status==='paid'||o.paid===true)return 'paid'; return 'new'}
function typeBadge(t){return '<span class="ob-type-badge ob-type-'+block_6492_esc(t||'bills')+'">'+block_6492_esc(TYPE_LABELS[t]||t||'-')+'</span>'}
function statusBadge(st,days){var label=STATUS_LABELS[st]||st; if(st==='new'){if(days<0)return '<span class="ob-status-badge ob-status-due">متأخر</span>'; if(days<=10)return '<span class="ob-status-badge ob-status-soon">قريب</span>'; return '<span class="ob-status-badge ob-status-ok">جديد</span>'} var cls=st==='paid'?'ok':st==='paused'?'soon':st==='deleted'?'due':'ok'; return '<span class="ob-status-badge ob-status-'+cls+'">'+block_6492_esc(label)+'</span>'}
function safe(v){return String(v||'').replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
function obActionButton(cls,action,id,label){return '<button type="button" class="ob-mini-btn '+block_6492_esc(cls||'')+'" data-obligation-action="'+block_6492_esc(action)+'" data-obligation-id="'+block_6492_esc(id)+'">'+block_6492_esc(label)+'</button>'}
function actions(o,opts){opts=opts||{}; var st=obligationStatusNorm(o),oid=String((o&&o.id)||''),h=[]; if(!opts.hideUnpay&&st==='paid'){h.push(obActionButton('ob-unpay','unpay',oid,'إلغاء السداد'))} else if(st==='new'){h.push(obActionButton('','mark-paid',oid,'تم السداد')); if(!opts.hideUnpay&&o.lastPaidDate&&o.prevDueDate)h.push(obActionButton('ob-unpay','unpay',oid,'إلغاء آخر سداد'))} if(st==='paused')h.push(obActionButton('','resume',oid,'تفعيل')); else if(st!=='deleted')h.push(obActionButton('','pause',oid,'إيقاف')); if(st==='deleted'){h.push(obActionButton('','restore',oid,'استرجاع'));h.push(obActionButton('ob-hard-delete','permanent-delete',oid,'حذف نهائي'))}else{h.push(obActionButton('','edit',oid,'تعديل'));h.push(obActionButton('','delete',oid,'حذف'))} return '<div class="ob-actions">'+h.join('')+'</div>'}
function bindObligationsDelegates(){if(window.__PETATOE_OBLIGATIONS_DELEGATES_BOUND__)return; window.__PETATOE_OBLIGATIONS_DELEGATES_BOUND__=true; document.addEventListener('click',function(ev){var btn=ev.target&&ev.target.closest?ev.target.closest('[data-obligation-action]'):null; if(!btn)return; var action=btn.getAttribute('data-obligation-action')||'', id=btn.getAttribute('data-obligation-id')||''; var map={'unpay':window.petUnpayObligation,'mark-paid':window.petMarkObligationPaid,'resume':window.petResumeObligation,'pause':window.petPauseObligation,'restore':window.petRestoreObligation,'permanent-delete':window.petPermanentDeleteObligation,'edit':window.petEditObligation,'delete':window.petDeleteObligation}; if(typeof map[action]==='function'){ev.preventDefault(); map[action](id)}}); document.addEventListener('input',function(ev){var id=ev.target&&ev.target.id; if(id==='obHistorySearch'&&typeof window.petRenderObligationsHistory==='function')window.petRenderObligationsHistory()}); document.addEventListener('change',function(ev){var id=ev.target&&ev.target.id; if((id==='obHistoryStatus'||id==='obHistoryType')&&typeof window.petRenderObligationsHistory==='function')window.petRenderObligationsHistory()})}
function selected(el, fallback){return el&&el.value?el.value:fallback}
function availableYears(data){var ys={}; data.forEach(function(o){var d=block_6492_parseDate(o.dueDate||o.prevDueDate||o.lastPaidDate||o.createdAt); if(d)ys[d.getFullYear()]=true}); var list=Object.keys(ys).sort(); if(!list.length)list=[String(new Date().getFullYear())]; return list}
function ensureFilterOptions(){var data=arr(); var y=byId('obYearFilter'),m=byId('obMonthFilter'),t=byId('obTypeFilter'); if(!y||!m)return; var oldY=y.value||String(new Date().getFullYear()), oldM=m.value||String(new Date().getMonth()+1).padStart(2,'0'); var years=availableYears(data); if(years.indexOf(oldY)<0)oldY=years[years.length-1]; obligationReplaceOptions(y,years.map(function(v){return {value:v,label:v}}),oldY); var months={}; data.forEach(function(o){var d=block_6492_parseDate(o.dueDate); if(d && String(d.getFullYear())===String(oldY))months[String(d.getMonth()+1).padStart(2,'0')]=true}); var ml=Object.keys(months).sort(); if(!ml.length){for(var i=1;i<=12;i++)ml.push(String(i).padStart(2,'0'))} if(ml.indexOf(oldM)<0)oldM=ml[ml.length-1]||String(new Date().getMonth()+1).padStart(2,'0'); var monthNames=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر']; obligationReplaceOptions(m,ml.map(function(v){return {value:v,label:(monthNames[Number(v)-1]||v)+' '+oldY}}),oldM); if(t&&!t.value)t.value='all'}
function monthFilteredData(){ensureFilterOptions(); var y=selected(byId('obYearFilter'),String(new Date().getFullYear())); var m=selected(byId('obMonthFilter'),String(new Date().getMonth()+1).padStart(2,'0')); var tp=selected(byId('obTypeFilter'),'all'); return arr().filter(function(o){if(obligationStatusNorm(o)!=='new')return false; if(tp!=='all'&&o.type!==tp)return false; var d=block_6492_parseDate(o.dueDate); if(!d)return false; return String(d.getFullYear())===String(y)&&String(d.getMonth()+1).padStart(2,'0')===String(m)}).sort(function(a,b){return String(a.dueDate||'').localeCompare(String(b.dueDate||''))})}
function kpis(){var a=arr(), active=a.filter(function(o){return obligationStatusNorm(o)==='new'}), paid=a.filter(function(o){return obligationStatusNorm(o)==='paid'}), due=active.filter(function(o){return daysTo(o.dueDate)<0}), soon=active.filter(function(o){var d=daysTo(o.dueDate);return d>=0&&d<=10}), total=active.reduce(function(s,o){return s+Number(o.amount||0)},0); var el=byId('obligationKpis'); if(!el)return; obSafeHtml(el,'<div class="ob-kpi" style="--accent:var(--green)"><span>التزامات نشطة</span><b>'+active.length+'</b><small>قيد المتابعة</small></div><div class="ob-kpi" style="--accent:var(--red)"><span>متأخرة</span><b>'+due.length+'</b><small>تحتاج إجراء</small></div><div class="ob-kpi" style="--accent:var(--yellow)"><span>خلال 10 أيام</span><b>'+soon.length+'</b><small>تنبيهات قريبة</small></div><div class="ob-kpi" style="--accent:var(--cyan)"><span>مسددة</span><b>'+paid.length+'</b><small>يمكن إلغاء السداد</small></div><div class="ob-kpi" style="--accent:var(--purple)"><span>قيمة الالتزامات النشطة</span><b>'+petBlock6501_money(total)+'</b><small>إجمالي تقديري</small></div>','obligations kpis')}
window.renderObligationsPanel=function(){var body=byId('obligationsTableBody'); if(!body)return; ensureFilterOptions(); kpis(); var data=monthFilteredData(); var y=selected(byId('obYearFilter'),''),m=selected(byId('obMonthFilter'),''); var lab=byId('obligationMonthLabel'); if(lab)lab.textContent='الفترة المعروضة: '+(m||'--')+' / '+(y||'--'); if(!data.length){obSafeHtml(body,'<tr><td colspan="9"><div class="ob-empty">لا توجد التزامات مطابقة للفلاتر</div></td></tr>','obligations empty table')}else{obSafeHtml(body,data.map(function(o){var d=daysTo(o.dueDate),st=obligationStatusNorm(o);return '<tr><td>'+typeBadge(o.type)+'</td><td>'+block_6492_esc(o.name||'-')+'</td><td>'+petBlock6501_money(o.amount)+'</td><td>'+block_6492_esc(o.dueDate||'-')+'</td><td>'+(d===99999?'-':(d<0?'متأخر '+Math.abs(d)+' يوم':'باقي '+d+' يوم'))+'</td><td>'+block_6492_esc(FREQ_LABELS[o.frequency]||o.frequency||'-')+'</td><td>'+statusBadge(st,d)+'</td><td>'+block_6492_esc(o.owner||'-')+'</td><td>'+actions(o,{hideUnpay:true})+'</td></tr>'}).join(''),'obligations table')}
    renderObligationWarehouseLowStock();
ensureHistoryUI(); renderHistory();}
function renderNotifications(){var el=byId('obligationNotifications'); if(!el)return; var data=arr().filter(function(o){var st=obligationStatusNorm(o),d=daysTo(o.dueDate);return st==='new'&&d<=10}).sort(function(a,b){return daysTo(a.dueDate)-daysTo(b.dueDate)}).slice(0,20); if(!data.length){obSafeHtml(el,'<div class="ob-empty">لا توجد تنبيهات مستحقة حالياً</div>','obligations notifications empty');return} obSafeHtml(el,data.map(function(o){var d=daysTo(o.dueDate),cls=d<0?'due':'soon';return '<div class="ob-note-item '+cls+'"><div><b>'+block_6492_esc(o.name||'-')+'</b><span>'+block_6492_esc(TYPE_LABELS[o.type]||'-')+' • '+petBlock6501_money(o.amount)+' • '+(d<0?'متأخر '+Math.abs(d)+' يوم':'باقي '+d+' يوم')+'</span></div><small>'+block_6492_esc(o.dueDate||'-')+'</small></div>'}).join(''),'obligations notifications')}
function ensureHistoryUI(){var page=document.querySelector('#obHistoryTab')||document.querySelector('#obligations .obligations-page'); if(!page)return; var card=byId('obligationsHistoryCard'); if(!card){card=document.createElement('div');card.className='ob-card ob-history-card';card.id='obligationsHistoryCard';page.appendChild(card)} if(!byId('obligationsHistoryBody')){obSafeHtml(card,'<div class="ob-history-toolbar"><div><b>📚 سجل الالتزامات المسجلة بالكامل</b><small>يعرض كل الالتزامات بالحالات: جديد / متوقف / محذوف / مسدد.</small></div><div class="ob-status-filter-row"><input id="obHistorySearch" placeholder="بحث باسم الالتزام أو المسؤول"><select id="obHistoryStatus"><option value="all">كل الحالات</option><option value="new">جديد</option><option value="paused">متوقف</option><option value="paid">مسدد</option><option value="deleted">محذوف</option></select><select id="obHistoryType"><option value="all">كل الأنواع</option><option value="bills">فواتير</option><option value="gov">رسوم حكومية</option><option value="annual">رسوم واشتراكات سنوية</option></select></div></div><div class="table-wrap ob-history-table"><table><thead><tr><th>#</th><th>الحالة</th><th>النوع</th><th>اسم الالتزام</th><th>القيمة</th><th>الاستحقاق الحالي</th><th>الاستحقاق السابق</th><th>آخر سداد</th><th>التكرار</th><th>المسؤول</th><th>ملاحظات</th><th>إجراءات</th></tr></thead><tbody id="obligationsHistoryBody"></tbody></table></div>','obligations history shell')}}
function textMatch(o,q){if(!q)return true; q=String(q).toLowerCase(); return [o.name,o.owner,o.note,o.dueDate,o.prevDueDate,o.lastPaidDate].join(' ').toLowerCase().indexOf(q)>-1}
function renderHistory(){var body=byId('obligationsHistoryBody'); if(!body)return; var q=(byId('obHistorySearch')||{}).value||'',st=(byId('obHistoryStatus')||{}).value||'all',tp=(byId('obHistoryType')||{}).value||'all'; var data=arr().filter(function(o){var ns=obligationStatusNorm(o); if(st!=='all'&&ns!==st)return false; if(tp!=='all'&&o.type!==tp)return false; return textMatch(o,q)}).sort(function(a,b){return String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||''))}); if(!data.length){obSafeHtml(body,'<tr><td colspan="12"><div class="ob-empty">لا توجد التزامات مطابقة للفلاتر</div></td></tr>','obligations history empty');return} obSafeHtml(body,data.map(function(o,i){var st=obligationStatusNorm(o);return '<tr><td>'+(i+1)+'</td><td>'+statusBadge(st,daysTo(o.dueDate))+'</td><td>'+typeBadge(o.type)+'</td><td>'+block_6492_esc(o.name||'-')+'</td><td>'+petBlock6501_money(o.amount)+'</td><td>'+block_6492_esc(o.dueDate||'-')+'</td><td>'+block_6492_esc(o.prevDueDate||'-')+'</td><td>'+block_6492_esc(o.lastPaidDate||'-')+'</td><td>'+block_6492_esc(FREQ_LABELS[o.frequency]||o.frequency||'-')+'</td><td>'+block_6492_esc(o.owner||'-')+'</td><td>'+block_6492_esc(o.note||'-')+'</td><td>'+actions(o)+'</td></tr>'}).join(''),'obligations history rows')}

function getWarehouseLowStockRows(){try{if(window.PETATOEWarehouseAlerts&&typeof window.PETATOEWarehouseAlerts.getRows==='function'){var rows=window.PETATOEWarehouseAlerts.getRows();return Array.isArray(rows)?rows:[]}}catch(e){window.PETATOEUtils&&window.PETATOEUtils.warnSilentCatch&&window.PETATOEUtils.warnSilentCatch("obligations/obligations-core.js",e);}return null}
function renderObligationWarehouseLowStock(){var body=byId('obWarehouseLowStockBody'), hint=byId('obWarehouseLowStockHint'); if(!body)return; var rows=getWarehouseLowStockRows(); if(rows===null){obSafeHtml(body,'<tr><td colspan="8"><div class="ob-empty">جاري تحميل بيانات تقرير المخازن الأصلي...</div></td></tr>','obligations warehouse loading'); if(hint)hint.textContent='مصدر البيانات: تقرير ⚠️ تنبيهات الأرصدة المنخفضة داخل المخازن'; setTimeout(renderObligationWarehouseLowStock,700);return} if(hint)hint.textContent='مصدر البيانات: نفس بيانات تقرير ⚠️ تنبيهات الأرصدة المنخفضة في المخازن'; rows=rows.slice().sort(function(a,b){return Number(a.balance||0)-Number(b.balance||0)}); obSafeHtml(body,rows.map(function(r,i){var z=Number(r.balance||0)===0; return '<tr><td>'+(i+1)+'</td><td>'+block_6492_esc(r.store||'-')+'</td><td>'+block_6492_esc(r.code||'-')+'</td><td>'+block_6492_esc(r.item||'-')+'</td><td class="'+(z?'ob-low-zero':'ob-low-warn')+'">'+block_6492_esc(String(r.balance==null?'-':r.balance))+'</td><td>'+block_6492_esc(String(r.min==null?'-':r.min))+'</td><td>'+block_6492_esc(r.last?new Date(r.last).toLocaleString('ar-EG'):'لا توجد حركة')+'</td><td><span class="ob-status-badge '+(z?'ob-status-due':'ob-status-soon')+'">'+(z?'نفد الرصيد':'أقل من الحد')+'</span></td></tr>'}).join('') || '<tr><td colspan="8"><div class="ob-empty">لا توجد أصناف مخزنية أقل من حد التنبيه الحالي.</div></td></tr>','obligations warehouse rows')}
window.petRenderObligationsWarehouseLowStock=renderObligationWarehouseLowStock;
window.petRenderObligationsHistory=renderHistory;
window.petSetObligationTab=function(tab){
  tab=tab==='history'?'history':'monthly';
  document.querySelectorAll('#obligations .ob-tab-btn').forEach(function(btn){btn.classList.toggle('active',btn.getAttribute('data-ob-tab')===tab)});
  document.querySelectorAll('#obligations .ob-tab-panel').forEach(function(panel){panel.classList.toggle('active',panel.getAttribute('data-ob-panel')===tab)});
  if(tab==='history'){ensureHistoryUI();renderHistory();}
  if(tab==='monthly'){window.renderObligationsPanel&&window.renderObligationsPanel();}
};

window.petOpenObligationForm=function(){var c=byId('obligationFormCard'); if(c)c.style.display='block'; var t=byId('obligationFormTitle'); if(t)t.textContent=window.__editingObligationId?'تعديل التزام':'إضافة التزام جديد'; try{c&&c.scrollIntoView({behavior:'smooth',block:'center'})}catch(e){window.PETATOEUtils&&window.PETATOEUtils.warnSilentCatch&&window.PETATOEUtils.warnSilentCatch("obligations/obligations-core.js",e);}};
window.petCloseObligationForm=function(){var c=byId('obligationFormCard'); if(c)c.style.display='none'; window.__editingObligationId=null; petResetObligationForm()};
window.petResetObligationForm=function(){['obName','obAmount','obDue','obOwner','obNote'].forEach(function(x){var e=byId(x); if(e)e.value=''}); var t=byId('obType');if(t)t.value='bills'; var f=byId('obFrequency');if(f)f.value='1'; var tt=byId('obligationFormTitle');if(tt)tt.textContent='إضافة التزام جديد'; window.__editingObligationId=null};
window.petSaveObligation=function(){var name=(byId('obName')||{}).value||'', due=(byId('obDue')||{}).value||''; if(!name.trim()){toastMsg('اكتب اسم الالتزام');return} if(!due){toastMsg('اختار تاريخ الاستحقاق');return} var data=arr(), edit=window.__editingObligationId, o=null; if(edit)o=data.find(function(x){return String(x.id)===String(edit)}); if(!o){o={id:'obl_'+Date.now()+'_'+Math.random().toString(36).slice(2),createdAt:new Date().toISOString(),status:'new',active:true}; data.unshift(o)} o.name=name.trim(); o.type=(byId('obType')||{}).value||'bills'; o.amount=Number((byId('obAmount')||{}).value||0); o.dueDate=due; o.frequency=(byId('obFrequency')||{}).value||'1'; o.owner=(byId('obOwner')||{}).value||''; o.note=(byId('obNote')||{}).value||''; if(o.status==='deleted')o.status='new'; o.active=true; o.updatedAt=new Date().toISOString(); save(data); addMove(edit?'تعديل التزام':'إضافة التزام',o,'info'); window.__editingObligationId=null; petResetObligationForm(); var c=byId('obligationFormCard'); if(c)c.style.display='none'; renderObligationsPanel(); toastMsg('تم حفظ الالتزام')};
window.petEditObligation=function(oid){var o=arr().find(function(x){return String(x.id)===String(oid)}); if(!o){toastMsg('الالتزام غير موجود');return} window.__editingObligationId=o.id; petOpenObligationForm(); var map={obName:o.name||'',obAmount:o.amount||'',obDue:o.dueDate||'',obOwner:o.owner||'',obNote:o.note||''}; Object.keys(map).forEach(function(k){var e=byId(k); if(e)e.value=map[k]}); var t=byId('obType');if(t)t.value=o.type||'bills'; var f=byId('obFrequency');if(f)f.value=String(o.frequency||'1'); var tt=byId('obligationFormTitle');if(tt)tt.textContent='تعديل الالتزام: '+(o.name||'');};
window.petMarkObligationPaid=function(oid){var data=arr(),o=data.find(function(x){return String(x.id)===String(oid)}); if(!o)return; var old=o.dueDate||'', base=block_6492_parseDate(old)||petBlock6501_today(), months=Number(o.frequency||1), nd=addMonths(base,months); if(!Array.isArray(o.paymentHistory))o.paymentHistory=[]; o.paymentHistory.push({paidAt:iso(petBlock6501_today()),paidAtTime:new Date().toISOString(),paidDueDate:old,nextDueDate:iso(nd),amount:Number(o.amount||0),frequency:String(o.frequency||'1')}); o.status='new';o.paid=false;o.active=true;o.prevDueDate=old;o.unpaidRestoreDueDate=old;o.lastPaidDate=iso(petBlock6501_today());o.dueDate=iso(nd);o.updatedAt=new Date().toISOString();save(data);addMove('سداد وتجديد التزام',o,'info',{prevDueDate:old,nextDueDate:iso(nd)});renderObligationsPanel();toastMsg('تم تسجيل السداد وتجديد الاستحقاق القادم إلى '+iso(nd))};
window.petUnpayObligation=function(oid){var data=arr(),o=data.find(function(x){return String(x.id)===String(oid)}); if(!o)return; var hist=Array.isArray(o.paymentHistory)?o.paymentHistory:[], last=hist.length?hist.pop():null; var restore=(last&&last.paidDueDate)||o.unpaidRestoreDueDate||o.prevDueDate||o.dueDate; o.status='new';o.paid=false;o.active=true;o.dueDate=restore;o.lastPaidDate=hist.length?(hist[hist.length-1].paidAt||''):'';o.prevDueDate=hist.length?(hist[hist.length-1].paidDueDate||''):'';o.unpaidRestoreDueDate=o.prevDueDate||'';o.paymentHistory=hist;o.updatedAt=new Date().toISOString();save(data);addMove('إلغاء آخر سداد التزام',o,'warn',{restoredDueDate:restore});renderObligationsPanel();toastMsg('تم إلغاء آخر سداد ورجوع تاريخ الاستحقاق إلى '+restore)};
window.petPauseObligation=function(oid){var data=arr(),o=data.find(function(x){return String(x.id)===String(oid)}); if(!o)return; o.status='paused';o.paused=true;o.active=true;o.updatedAt=new Date().toISOString();save(data);addMove('إيقاف التزام',o,'warn');renderObligationsPanel()};
window.petResumeObligation=function(oid){var data=arr(),o=data.find(function(x){return String(x.id)===String(oid)}); if(!o)return; o.status='new';o.paused=false;o.active=true;o.updatedAt=new Date().toISOString();save(data);addMove('تفعيل التزام',o,'info');renderObligationsPanel()};
window.petDeleteObligation=function(oid){if(!confirm('حذف الالتزام؟ سيتم نقله لحالة محذوف ويمكن استرجاعه.'))return; var data=arr(),o=data.find(function(x){return String(x.id)===String(oid)}); if(!o)return; o.status='deleted';o.active=false;o.deletedAt=new Date().toISOString();o.updatedAt=new Date().toISOString();save(data);addMove('حذف التزام',o,'warn');renderObligationsPanel();toastMsg('تم نقل الالتزام إلى محذوف')};
window.petRestoreObligation=function(oid){var data=arr(),o=data.find(function(x){return String(x.id)===String(oid)}); if(!o)return; o.status='new';o.active=true;o.deletedAt='';o.updatedAt=new Date().toISOString();save(data);addMove('استرجاع التزام',o,'info');renderObligationsPanel()};
window.petPermanentDeleteObligation=function(oid){if(!confirm('حذف نهائي؟'))return; var data=arr(),ix=data.findIndex(function(x){return String(x.id)===String(oid)}); if(ix<0)return; var o=data[ix]; data.splice(ix,1);save(data);addMove('حذف نهائي لالتزام',o,'error');renderObligationsPanel();toastMsg('تم الحذف النهائي')};
window.petRequestObligationNotificationPermission=function(){if(!('Notification' in window)){toastMsg('المتصفح لا يدعم الإشعارات');return} Notification.requestPermission().then(function(){toastMsg('تم تحديث صلاحية الإشعارات')})};
window.petSaveObligationEmailSettings=function(){var email=(byId('obEmailTo')||{}).value||''; obligationsWriteJson(EMAIL_KEY,{email:email,enabled:!!email,updatedAt:new Date().toISOString()}); toastMsg(email?'تم حفظ إعداد الإيميل':'اكتب إيميل صحيح')};
window.petOpenDueObligationsEmail=function(){var s=obligationsReadJson(EMAIL_KEY,{}), email=(byId('obEmailTo')||{}).value||s.email||''; var due=arr().filter(function(o){return obligationStatusNorm(o)==='new'&&daysTo(o.dueDate)<=10}); var body=due.map(function(o){return '- '+(o.name||'-')+' | '+petBlock6501_money(o.amount)+' | '+(o.dueDate||'-')}).join('%0D%0A'); window.location.href='mailto:'+encodeURIComponent(email)+'?subject='+encodeURIComponent('تنبيه الالتزامات المستحقة')+'&body='+body};
window.petExportObligationsExcel=function(){try{var data=arr().map(function(o){return {'الحالة':STATUS_LABELS[obligationStatusNorm(o)]||obligationStatusNorm(o),'النوع':TYPE_LABELS[o.type]||o.type,'اسم الالتزام':o.name,'القيمة':o.amount,'الاستحقاق':o.dueDate,'التكرار':FREQ_LABELS[o.frequency]||o.frequency,'المسؤول':o.owner,'ملاحظات':o.note}}); if(window.XLSX){var ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Obligations');XLSX.writeFile(wb,'PETATOE_obligations.xlsx')}else toastMsg('مكتبة Excel غير محملة')}catch(e){console.error(e);toastMsg('تعذر تصدير Excel')}};
function boot(){try{bindObligationsDelegates();obligationsLoadRemote().then(function(){try{ensureFilterOptions();ensureHistoryUI();renderObligationsPanel();renderObligationWarehouseLowStock();setTimeout(renderObligationWarehouseLowStock,800);setTimeout(renderObligationWarehouseLowStock,1800);var em=byId('obEmailTo'),s=obligationsReadJson(EMAIL_KEY,{});if(em&&s.email)em.value=s.email}catch(e){console.error('Obligations boot async error',e)}})}catch(e){console.error('Obligations boot error',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(boot,120)});else setTimeout(boot,120);
window.petObligationsBoot=boot;document.addEventListener('petatoe:tabchange',function(e){if(e.detail&&e.detail.tabId==='obligations')setTimeout(boot,150)});document.addEventListener('petatoe:warehouse:movement-saved',function(){setTimeout(renderObligationWarehouseLowStock,150)});document.addEventListener('petatoe:warehouse:ui-rendered',function(){setTimeout(renderObligationWarehouseLowStock,150)});
})();
