/* PETATOE v9 i18n Arabic dictionary
   Scope: Phase 3A shell/dashboard foundation. */
(function(){
  'use strict';
  window.PETATOE_I18N_DICTIONARIES = window.PETATOE_I18N_DICTIONARIES || {};
  window.PETATOE_I18N_DICTIONARIES.ar = {
    meta:{code:'ar',label:'عربي',dir:'rtl'},
    app:{name:'PETATOE',subtitle:'Analytics System'},
    language:{button:'AR',toggleTitle:'اختيار اللغة',menuLabel:'اختيار اللغة',arabic:'عربي',english:'English'},
    topbar:{reports:'📑 التقارير',pdf:'📊 تقرير PDF',searchTitle:'بحث',searchOpen:'فتح البحث',launcherTitle:'فتح القائمة الرئيسية',notifications:'الإشعارات',loading:'جارٍ التحميل'},
    globalSearch:{placeholder:'🔍 ابحث عن عميل، خدمة، سيارة، فاتورة...', shortcut:'ESC للإغلاق | Enter للانتقال | Ctrl+K أو / للفتح'},
    dashboard:{title:'Dashboard',subtitle:'لوحة متابعة مبيعات PETATOE بالريال السعودي',monthlySales:'📊 المبيعات الشهرية',topServices:'📦 أعلى الخدمات مبيعاً',topClients:'🏆 أعلى العملاء إنفاقاً',paymentSales:'💳 المبيعات حسب طريقة الدفع',vansComparison:'🚐 مقارنة السيارات',quickInsights:'⚡ مؤشرات سريعة',totalSales:'إجمالي المبيعات',salesBeforeVat:'المبيعات قبل الضريبة',vat:'الضريبة',operationsCount:'عدد العمليات',customersCount:'عدد العملاء',averageInvoice:'متوسط الفاتورة',allYearsMetric:'• مؤشر إجمالي لكل السنوات',noChange:'• لا يوجد تغير',newMetric:'▲ جديد 100%',increase:'زيادة',decrease:'انخفاض',comparedSamePeriod:'مقارنة بنفس المدة',period:'الفترة',invoiceCount:'عدد الفواتير',bestMonth:'أفضل شهر',averageBeforeVat:'متوسط قبل الضريبة',totalVat:'إجمالي الضريبة',includingVat:'شامل الضريبة',beforeVat:'قبل الضريبة',operatingDays:'أيام التشغيل',dailyAverageOperations:'متوسط عمليات يومي',totalCustomers:'إجمالي العملاء',averageOperationsPerCustomer:'متوسط عمليات/عميل',topPaymentMethod:'أفضل طريقة دفع',bestService:'أفضل خدمة',bestPerforming:'الأفضل أداءً',mostRequestedService:'أكثر خدمة طلباً',total:'الإجمالي',vehicle:'سيارة',best:'🏆 الأفضل',noData:'لا توجد بيانات',operationUnit:'عملية',averageLabel:'متوسط',totalSalesDesc:'يعرض إجمالي قيمة المبيعات للفترة أو السنة المختارة من الشاشة الرئيسية.',salesBeforeVatDesc:'إجمالي قيمة المبيعات قبل الضريبة كما هي مسجلة في بيانات الإدخال أو ملف Excel.',vatDesc:'إجمالي قيمة الضريبة من العمود الأصلي في البيانات بدون أي معادلات داخل التقرير.',operationsCountDesc:'إجمالي عدد سطور/عمليات البيع المسجلة بعد تطبيق فلاتر الشاشة الرئيسية.',customersCountDesc:'عدد العملاء الفريدين داخل الفترة المختارة بعد تطبيق الفلاتر.',averageInvoiceDesc:'متوسط قيمة الفاتورة = إجمالي المبيعات مقسوم على عدد الفواتير الفريدة.'},
    actions:{refresh:'🔄 تحديث',exportPagePdf:'🖨️ تصدير الصفحة PDF',reset:'Reset 🔄'},
    filters:{allYears:'كل السنوات',allMonths:'كل الشهور',allVehicles:'كل السيارات',allPayments:'كل طرق الدفع'},
    payroll:{manage:'إدارة الرواتب',manageSub:'إنشاء كشوف الرواتب والاعتمادات',slip:'كشف الراتب',slipSub:'عرض كشف راتب المستخدم الحالي فقط'},
    sidebar:{appointments:'📅 إدارة المواعيد',operations:'⚙️ إدارة التشغيل',home:'🏠 الرئيسية',children:'👨‍👧‍👦 مصروفات الأبناء',transactions:'⭐ العمليات',dataEntry:'➕ إدخال البيانات',excelUpload:'📤 رفع Excel',records:'📋 السجلات',auditLog:'🧾 سجل الحركات',analytics:'📈 التحليلات',smartReports:'🧠 التقارير الذكية',customer360:'👤 Customer 360',commissions:'💰 نظام العمولات',commissionStatement:'📄 كشف العمولة',management:'🏢 الإدارة',executive:'👑 الإدارة العليا',obligations:'💳 الالتزامات',payroll:'💼 إدارة الرواتب',salarySlip:'📄 كشف الراتب',fleet:'🚚 إدارة السيارات',treasury:'🏦 الخزينة',warehouses:'📦 المخازن',system:'⚙️ النظام',settings:'⚙️ الإعدادات',tagline:'Care. Love. PETATOE.',petCareText:'🐾 نهتم بحيواناتك الأليفة',changeImage:'📷 تغيير الصورة',originalImage:'↩️ الأصلية'},
    exports:{pdf:'🖨️ PDF',excel:'⬇️ Excel'},
    sales:{title:'Sales Analytics',subtitle:'تحليل تفصيلي للمبيعات الشهرية والربعية',monthlyTrend:'Monthly Trend',monthlyTrendNote:'الشكل المعتمد: قيم واضحة فوق الأعمدة بدون تداخل',quarterlyComparison:'Quarterly Comparison (آخر سنتين متاحتين) 🗓️',quarterlyNote:'كل ربع من السنة السابقة بجانب آخر سنة متاحة، والقيم فوق كل عمود',quarterDetails:'📊 تفاصيل الأرباع'},
    vans:{title:'Vans Performance',subtitle:'تقارير السيارات بقيم واضحة وفلاتر سنة / كل السنوات',salesDistribution:'🥧 توزيع مبيعات السيارات',monthlyPerformance:'📈 أداء السيارات الشهري',pointValuesNote:'القيم منفصلة فوق النقاط بدون تداخل',monthlySales:'🚐 مبيعات السيارات شهرياً',groupedBarsNote:'أعمدة مجمعة مع إجمالي المبيعات لكل شهر',sarNote:'جميع القيم بالريال السعودي وتشمل ضريبة القيمة المضافة',details:'تفاصيل السيارات'},
    services:{title:'Services Analysis',subtitle:'تحليل الخدمات الأكثر طلبًا والأعلى قيمة',topServices:'🧩 Top Services'},
    smart:{title:'🧠 Smart Reports Center',subtitle:'تقارير ذكية مستقلة تضيف عمق تحليلي للنشاط بدون التأثير على التقارير القديمة أو شكلها.',exportPagePdf:'🖨️ تصدير الصفحة PDF',exportData:'⬇️ تصدير البيانات',refresh:'🔄 تحديث التقارير الذكية'},
    customer360:{title:'Customer 360°',subtitle:'ملف كامل لكل عميل: المبيعات، الفواتير، الخدمات، الزيارات، وآخر تعامل.',searchPlaceholder:'ابحث باسم العميل...',clearSearch:'مسح البحث',empty:'اختر عميل من القائمة لعرض ملفه الكامل.'},
    audit:{title:'Audit Log',subtitle:'سجل متابعة لكل الحركات المهمة داخل النسخة الحالية.',clearLog:'🗑️ مسح السجل'},
    entry:{title:'Data Entry',newRecord:'إدخال سجل جديد',save:'✅ حفظ السجل',clear:'🧹 مسح الفورم'},
    import:{title:'Excel Upload',subtitle:'نظام رفع متعدد المصادر مع منع التكرار وفحص الخلايا قبل الاعتماد',downloadTemplate:'⬇️ تحميل التمبلت',fullTitle:'📘 رفع تقرير تفصيلي شامل',fullDesc:'كل بيانات الفواتير والبنود وطريقة الدفع مرة واحدة.',itemsTitle:'🧾 مبيعات البنود حسب التصنيف',itemsDesc:'بيانات البنود التفصيلية بدون طريقة الدفع.',paymentsTitle:'💳 تحديد طريقة المدفوعات',paymentsDesc:'ربط طريقة الدفع برقم الفاتورة للبيانات المرفوعة.',workflowNote:'اختر طريقة الرفع ثم ارفع ملف Excel. سيتم منع الرفع عند وجود تكرار أو بيانات ناقصة.',dropTitle:'اسحب ملف التقرير التفصيلي الشامل هنا أو اضغط للاختيار',dropDesc:'يدعم نفس ترتيب ملف البيانات الأساسية — xlsx / xls / csv',previewTitle:'معاينة أول 30 سجل',append:'✅ إضافة للبيانات الحالية',replace:'♻️ استبدال البيانات'},
    records:{title:'Records',subtitle:'إدارة السجلات مع تعديل وحذف وتصدير',exportAll:'⬇️ Excel الكل',exportFiltered:'⬇️ Excel المصفّى',print:'🖨️ طباعة',deleteAll:'🗑️ حذف الكل',searchPlaceholder:'بحث في السجلات...',previous:'السابق',next:'التالي'},
    charts:{bar:'Bar',line:'Line'}
  };
})();
