/* PETATOE v9 i18n English dictionary
   Scope: Phase 3A shell/dashboard foundation. This file must contain English UI text only. */
(function(){
  'use strict';
  window.PETATOE_I18N_DICTIONARIES = window.PETATOE_I18N_DICTIONARIES || {};
  window.PETATOE_I18N_DICTIONARIES.en = {
    meta:{code:'en',label:'English',dir:'ltr'},
    app:{name:'PETATOE',subtitle:'Analytics System'},
    language:{button:'EN',toggleTitle:'Choose language',menuLabel:'Choose language',arabic:'Arabic',english:'English'},
    topbar:{reports:'📑 Reports',pdf:'📊 PDF Report',searchTitle:'Search',searchOpen:'Open search',launcherTitle:'Open main menu',notifications:'Notifications',loading:'Loading'},
    globalSearch:{placeholder:'🔍 Search customer, service, vehicle, or invoice...', shortcut:'ESC to close | Enter to open | Ctrl+K or / to search'},
    dashboard:{title:'Dashboard',subtitle:'PETATOE sales dashboard in Saudi Riyal',monthlySales:'📊 Monthly Sales',topServices:'📦 Top Selling Services',topClients:'🏆 Top Spending Customers',paymentSales:'💳 Sales by Payment Method',vansComparison:'🚐 Vehicle Comparison',quickInsights:'⚡ Quick Insights',totalSales:'Total Sales',salesBeforeVat:'Sales Before VAT',vat:'VAT',operationsCount:'Operations Count',customersCount:'Customers Count',averageInvoice:'Average Invoice',allYearsMetric:'• Total metric for all years',noChange:'• No change',newMetric:'▲ New 100%',increase:'increase',decrease:'decrease',comparedSamePeriod:'compared with the same period',period:'Period',invoiceCount:'Invoice Count',bestMonth:'Best Month',averageBeforeVat:'Average Before VAT',totalVat:'Total VAT',includingVat:'Including VAT',beforeVat:'Before VAT',operatingDays:'Operating Days',dailyAverageOperations:'Daily Average Operations',totalCustomers:'Total Customers',averageOperationsPerCustomer:'Average Operations per Customer',topPaymentMethod:'Top Payment Method',bestService:'Best Service',bestPerforming:'Best Performing',mostRequestedService:'Most Requested Service',total:'Total',vehicle:'Vehicle',best:'🏆 Best',noData:'No data available',operationUnit:'operation',averageLabel:'Average',totalSalesDesc:'Shows total sales value for the selected period or year on the main dashboard.',salesBeforeVatDesc:'Total sales value before VAT as recorded in the imported Excel file or manual data entry.',vatDesc:'Total VAT value from the original data column without report-side recalculation.',operationsCountDesc:'Total number of sales rows or operations after applying the main dashboard filters.',customersCountDesc:'Unique customers within the selected period after applying filters.',averageInvoiceDesc:'Average invoice value equals total sales divided by unique invoice count.'},
    actions:{refresh:'🔄 Refresh',exportPagePdf:'🖨️ Export Page PDF',reset:'Reset 🔄'},
    filters:{allYears:'All Years',allMonths:'All Months',allVehicles:'All Vehicles',allPayments:'All Payment Methods'},
    payroll:{manage:'Payroll Management',manageSub:'Create payroll statements and approvals',slip:'Payroll Statement',slipSub:'Show the current user payroll statement only'},
    sidebar:{appointments:'📅 Appointments Management',operations:'⚙️ Operations Management',home:'🏠 Home',children:'👨‍👩‍👧 Children Expenses',transactions:'⭐ Transactions',dataEntry:'➕ Data Entry',excelUpload:'📤 Excel Upload',records:'📋 Records',auditLog:'🧾 Audit Log',analytics:'📈 Analytics',smartReports:'🧠 Smart Reports',customer360:'👤 Customer 360',commissions:'💰 Commissions System',commissionStatement:'📄 Commission Statement',management:'🏢 Management',executive:'👑 Executive Management',obligations:'💳 Obligations',payroll:'💼 Payroll Management',salarySlip:'📄 Payroll Statement',fleet:'🚚 Fleet Management',treasury:'🏦 Treasury',warehouses:'📦 Warehouses',system:'⚙️ System',settings:'⚙️ Settings',tagline:'Care. Love. PETATOE.',petCareText:'🐾 We care for your pets',changeImage:'📷 Change Image',originalImage:'↩️ Original'},
    exports:{pdf:'🖨️ PDF',excel:'⬇️ Excel'},
    sales:{title:'Sales Analytics',subtitle:'Detailed monthly and quarterly sales analysis',monthlyTrend:'Monthly Trend',monthlyTrendNote:'Approved view: clear values above bars without overlap',quarterlyComparison:'Quarterly Comparison (latest two available years) 🗓️',quarterlyNote:'Each quarter from the previous year appears next to the latest available year, with values above each bar',quarterDetails:'📊 Quarter Details'},
    vans:{title:'Vans Performance',subtitle:'Vehicle reports with clear values and year / all-years filters',salesDistribution:'🥧 Vehicle Sales Distribution',monthlyPerformance:'📈 Monthly Vehicle Performance',pointValuesNote:'Values are separated above points without overlap',monthlySales:'🚐 Monthly Vehicle Sales',groupedBarsNote:'Grouped bars with total sales for each month',sarNote:'All values are in Saudi Riyal and include VAT',details:'Vehicle Details'},
    services:{title:'Services Analysis',subtitle:'Analysis of most requested and highest-value services',topServices:'🧩 Top Services'},
    smart:{title:'🧠 Smart Reports Center',subtitle:'Independent smart reports that add analytical depth without affecting legacy reports or their layout.',exportPagePdf:'🖨️ Export Page PDF',exportData:'⬇️ Export Data',refresh:'🔄 Refresh Smart Reports'},
    customer360:{title:'Customer 360°',subtitle:'A complete customer profile: sales, invoices, services, visits, and last interaction.',searchPlaceholder:'Search by customer name...',clearSearch:'Clear Search',empty:'Select a customer from the list to view the full profile.'},
    audit:{title:'Audit Log',subtitle:'A tracking log for all important actions in the current version.',clearLog:'🗑️ Clear Log'},
    entry:{title:'Data Entry',newRecord:'New record entry',save:'✅ Save Record',clear:'🧹 Clear Form'},
    import:{title:'Excel Upload',subtitle:'Multi-source upload system with duplicate prevention and cell validation before approval',downloadTemplate:'⬇️ Download Template',fullTitle:'📘 Upload Full Detailed Report',fullDesc:'All invoice, line item, and payment method data in one upload.',itemsTitle:'🧾 Item Sales by Category',itemsDesc:'Detailed line item data without payment method information.',paymentsTitle:'💳 Payment Method Assignment',paymentsDesc:'Map payment methods to invoice numbers for uploaded data.',workflowNote:'Choose the upload method, then upload the Excel file. Upload will be blocked when duplicates or missing data are found.',dropTitle:'Drop the full detailed report here or click to choose',dropDesc:'Supports the same structure as the main data file — xlsx / xls / csv',previewTitle:'Preview First 30 Records',append:'✅ Append to Current Data',replace:'♻️ Replace Data'},
    records:{title:'Records',subtitle:'Manage records with edit, delete, and export actions',exportAll:'⬇️ All Excel',exportFiltered:'⬇️ Filtered Excel',print:'🖨️ Print',deleteAll:'🗑️ Delete All',searchPlaceholder:'Search records...',previous:'Previous',next:'Next'},
    charts:{bar:'Bar',line:'Line'}
  };
})();
