(function(){
  'use strict';
  var root=window.PETATOE_I18N_DICTIONARIES=window.PETATOE_I18N_DICTIONARIES||{};
  root.ar=root.ar||{}; root.en=root.en||{};
  root.ar.maintenanceSource={
    unavailable:'غير متاح',ready:'جاهز',needsReview:'يحتاج مراجعة',available:'متاح',notAvailable:'غير متاح',loaded:'محمل',notLoaded:'غير محمل',present:'موجود',notDetected:'لم يتم رصده',active:'فعال',missing:'غير متاح',certified:'معتمد',review:'مراجعة',file:'ملف',candidate:'مرشح',internal:'داخلي',external:'خارجي',
    centerTitle:'🛠️ مركز صيانة وتشخيص النظام',buttonLabel:'🛠️ صيانة',buttonTitle:'مركز صيانة وتشخيص النظام',copyReport:'نسخ التقرير',exportTxt:'تصدير TXT',exportJson:'تصدير JSON',refresh:'تحديث',close:'إغلاق',diagnosticsStatus:'حالة التشخيص',runtimeEvents:'أحداث التشغيل',latestRuntimeEvents:'آخر أحداث التشغيل',latestErrors:'آخر الأخطاء',errors:'الأخطاء',scripts:'السكريبتات',blockingJs:'ملفات JavaScript الحاجبة',silentCatch:'الاستثناءات الصامتة',innerHtmlRisk:'مخاطر innerHTML',lazyLoading:'التحميل الكسول',structuralCleanup:'التنظيف الهيكلي',runtimeGuards:'حمايات التشغيل',regressionScore:'درجة اختبارات الانحدار',stylesheets:'ملفات التنسيق',storageKeys:'مفاتيح التخزين',coreComponentsStatus:'حالة المكونات الأساسية',lastRuntimeEvents:'آخر أحداث التشغيل',jsFilesLoaded:'ملفات JavaScript المحملة',cssFiles:'ملفات CSS',noDeferAsyncModule:'بدون defer/async/module',noDeletion:'بدون حذف',localSession:'محلي / جلسة',noCapturedErrors:'لا توجد أخطاء ملتقطة حاليًا.',noRuntimeEvents:'لا توجد أحداث بعد.',lastCheck:'آخر فحص',readOnlyScreen:'هذه الشاشة لا تعدل بيانات البرنامج.',time:'الوقت',level:'المستوى',source:'المصدر',message:'الرسالة',
    diagnosticsCore:'نواة التشخيص',routerPresence:'وجود الموجّه',permissionsSurface:'واجهة الصلاحيات',browserOnline:'اتصال المتصفح',lazyFoundation:'أساس التحميل الكسول',runtimeHardening:'تقوية التشغيل',regressionSuite:'حزمة اختبارات الانحدار',optimizedBaseline:'خط الأساس المحسن',greenBaseline:'خط الأساس الأخضر',finalBaseline:'خط الأساس النهائي',healthLevel:'مستوى الصحة',
    copyDialogTitle:'نسخ تقرير الصيانة',copyDialogHint:'تم تجهيز التقرير بالكامل وتحديده. اضغط Ctrl + C إذا لم يتم النسخ تلقائيًا.',copyNow:'نسخ الآن',copySuccess:'تم نسخ التقرير بنجاح',copyAutoBlocked:'لم يسمح المتصفح بالنسخ التلقائي — اضغط Ctrl + C',copyComplete:'تم نسخ تقرير الصيانة بالكامل',copyManualHint:'لو لم يتم النسخ تلقائيًا، التقرير محدد بالكامل الآن. اضغط Ctrl + C أو زر "نسخ الآن".',copyManualOpened:'تم فتح مربع النسخ اليدوي — اضغط Ctrl + C',openFailed:'تعذر فتح مركز الصيانة. راجع Console.'
  };
  root.en.maintenanceSource={
    unavailable:'Unavailable',ready:'Ready',needsReview:'Needs review',available:'Available',notAvailable:'Unavailable',loaded:'Loaded',notLoaded:'Not loaded',present:'Present',notDetected:'Not detected',active:'Active',missing:'Missing',certified:'Certified',review:'Review',file:'file',candidate:'candidate',internal:'Internal',external:'External',
    centerTitle:'🛠️ System Maintenance and Diagnostics Center',buttonLabel:'🛠️ Maintenance',buttonTitle:'System Maintenance and Diagnostics Center',copyReport:'Copy report',exportTxt:'Export TXT',exportJson:'Export JSON',refresh:'Refresh',close:'Close',diagnosticsStatus:'Diagnostics status',runtimeEvents:'Runtime events',latestRuntimeEvents:'Latest runtime events',latestErrors:'Latest errors',errors:'Errors',scripts:'Scripts',blockingJs:'Blocking JavaScript',silentCatch:'Silent catches',innerHtmlRisk:'innerHTML risk',lazyLoading:'Lazy loading',structuralCleanup:'Structural cleanup',runtimeGuards:'Runtime guards',regressionScore:'Regression score',stylesheets:'Stylesheets',storageKeys:'Storage keys',coreComponentsStatus:'Core components status',lastRuntimeEvents:'Latest runtime events',jsFilesLoaded:'Loaded JavaScript files',cssFiles:'CSS files',noDeferAsyncModule:'Without defer/async/module',noDeletion:'No deletion',localSession:'local / session',noCapturedErrors:'No captured errors at this time.',noRuntimeEvents:'No runtime events yet.',lastCheck:'Last check',readOnlyScreen:'This screen does not modify application data.',time:'Time',level:'Level',source:'Source',message:'Message',
    diagnosticsCore:'Diagnostics core',routerPresence:'Router presence',permissionsSurface:'Permissions surface',browserOnline:'Browser online',lazyFoundation:'Lazy foundation',runtimeHardening:'Runtime hardening',regressionSuite:'Regression suite',optimizedBaseline:'Optimized baseline',greenBaseline:'Green baseline',finalBaseline:'Final baseline',healthLevel:'Health level',
    copyDialogTitle:'Copy maintenance report',copyDialogHint:'The complete report is ready and selected. Press Ctrl + C if it is not copied automatically.',copyNow:'Copy now',copySuccess:'Report copied successfully',copyAutoBlocked:'The browser did not allow automatic copying — press Ctrl + C',copyComplete:'The full maintenance report was copied',copyManualHint:'If the report was not copied automatically, it is fully selected now. Press Ctrl + C or the “Copy now” button.',copyManualOpened:'The manual copy dialog is open — press Ctrl + C',openFailed:'Unable to open the Maintenance Center. Check the Console.'
  };
  try{if(window.PETATOE_LOCALIZATION_CENTER&&typeof window.PETATOE_LOCALIZATION_CENTER.registerModule==='function'){window.PETATOE_LOCALIZATION_CENTER.registerModule('maintenanceSource',{ar:root.ar.maintenanceSource,en:root.en.maintenanceSource});}}catch(e){}
})();
