(function(){
'use strict';
var FLEET_KEY='fleet';
var FLEET_TABLE='operations_master_data';
var fleetRemoteState={hydrated:false,loading:false,saving:false,cache:{vehicles:[],events:[],seq:1}};
function repo(){return window.PETATOESupabaseRepository||null}
function clone(v){try{return JSON.parse(JSON.stringify(v))}catch(e){return v}}
function fleetNormalizeStore(raw){var s=Object.assign({vehicles:[],events:[],seq:1},raw&&typeof raw==='object'?raw:{});if(!Array.isArray(s.vehicles))s.vehicles=[];if(!Array.isArray(s.events))s.events=[];s.seq=Number(s.seq||1)||1;return s}
function fleetHydrateRemote(){try{var r=repo();if(fleetRemoteState.hydrated||fleetRemoteState.loading||!r||typeof r.getSingleton!=='function')return;fleetRemoteState.loading=true;r.getSingleton(FLEET_TABLE,FLEET_KEY,{vehicles:[],events:[],seq:1}).then(function(data){fleetRemoteState.cache=fleetNormalizeStore(data);fleetRemoteState.hydrated=true;fleetRemoteState.loading=false;try{if(document.getElementById('fleet'))render()}catch(e){window.PETATOEUtils&&window.PETATOEUtils.warnSilentCatch&&window.PETATOEUtils.warnSilentCatch('fleet remote render',e)}}).catch(function(e){fleetRemoteState.loading=false;console.warn('PETATOE Fleet Supabase load failed',e)})}catch(e){fleetRemoteState.loading=false;console.warn('PETATOE Fleet Supabase hydrate failed',e)}}
function fleetPersistRemote(s){fleetRemoteState.cache=fleetNormalizeStore(s);try{var r=repo();if(!r||typeof r.saveSingleton!=='function'){console.warn('PETATOE Fleet Supabase repository not ready; local fallback disabled');if(typeof toast==='function')toast('تعذر حفظ بيانات الأسطول: اتصال Supabase غير جاهز');return false}fleetRemoteState.saving=true;r.saveSingleton(FLEET_TABLE,FLEET_KEY,clone(fleetRemoteState.cache)).then(function(){fleetRemoteState.saving=false}).catch(function(e){fleetRemoteState.saving=false;console.warn('PETATOE Fleet Supabase save failed',e);if(typeof toast==='function')toast('فشل حفظ بيانات الأسطول في Supabase')});return true}catch(e){fleetRemoteState.saving=false;console.warn('PETATOE Fleet Supabase persist failed',e);if(typeof toast==='function')toast('فشل حفظ بيانات الأسطول في Supabase');return false}}
var charts={};
var state={tab:'overview',period:'',vehicle:'all'};
function $(id){return document.getElementById(id)}
function html(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function fleetSafeRender(target, markup, reason){var el=(typeof target==='string')?$(target):target;if(!el)return false;try{if(window.PETATOESafeRender&&typeof window.PETATOESafeRender.htmlTrusted==='function')return window.PETATOESafeRender.htmlTrusted(el,String(markup==null?'':markup),reason||'fleet trusted escaped template')}catch(e){window.PETATOEUtils&&window.PETATOEUtils.warnSilentCatch&&window.PETATOEUtils.warnSilentCatch('fleet safe render fallback',e)}try{el.textContent='';el.insertAdjacentHTML('beforeend',String(markup==null?'':markup));return true}catch(e2){window.PETATOEUtils&&window.PETATOEUtils.warnSilentCatch&&window.PETATOEUtils.warnSilentCatch('fleet safe render failed',e2);return false}}
function n(v){if(typeof parseNum==='function')return parseNum(v);var x=Number(String(v||0).replace(/,/g,''));return isNaN(x)?0:x}
function f0(v){return (typeof fmt0==='function')?fmt0(v):Math.round(n(v)).toLocaleString('en-US')}
function cash(v){return (typeof money==='function')?money(v):(Number(n(v)).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})+' SAR')}
function petBlock5491_today(){return (window.PETATOEDate&&PETATOEDate.todayString)?PETATOEDate.todayString():new Date().toISOString().slice(0,10)}
function thisMonth(){return petBlock5491_today().slice(0,7)}
function monthKey(d){var s=String(d||'');var m=s.match(/^(\d{4})-(\d{2})/);return m?m[1]+'-'+m[2]:''}
function daysInMonth(k){var m=String(k||'').match(/^(\d{4})-(\d{2})$/);return m?new Date(+m[1],+m[2],0).getDate():30}
function recs(){try{return window.PETATOEDataSource.getRecordsSync()||[]}catch(e){return []}}
function vanOf(r){return String((r&&r.van)||'').trim()||'غير محدد'}
function uniqueVans(){var o={};recs().forEach(function(r){var v=vanOf(r);if(v&&v!=='غير محدد')o[v]=1});return Object.keys(o).sort()}
function makeId(name,i){return 'van-'+i+'-'+String(name).replace(/[^a-zA-Z0-9\u0600-\u06FF]+/g,'-')}
function defaults(){return uniqueVans().map(function(v,i){return {id:makeId(v,i+1),name:v,plate:v,driver:'',groomer:'',model:'',year:'',status:'active',startDate:'',notes:'تمت إضافتها تلقائياً من بيانات المبيعات'}})}
function fleetReadStore(){fleetHydrateRemote();var s=fleetNormalizeStore(fleetRemoteState.cache);var changed=false;if(!s.vehicles.length){s.vehicles=defaults();s.seq=s.vehicles.length+1;if(fleetRemoteState.hydrated)changed=true}else{var known={};s.vehicles.forEach(function(v){known[String(v.name||v.plate||'').trim()]=1});uniqueVans().forEach(function(v){if(!known[v]){s.vehicles.push({id:'van-'+Date.now()+'-'+Math.random().toString(16).slice(2),name:v,plate:v,driver:'',groomer:'',model:'',year:'',status:'active',startDate:'',notes:'تمت إضافتها تلقائياً من بيانات المبيعات'});changed=true;}})}fleetRemoteState.cache=s;if(changed)fleetWriteStore(s);return s}
function fleetWriteStore(s){return fleetPersistRemote(s)}
function vehicles(){return fleetReadStore().vehicles}
function events(){return fleetReadStore().events}
function vehById(id){return vehicles().filter(function(v){return String(v.id)===String(id)})[0]||null}
function vehName(id){var v=vehById(id);return v?(v.name||v.plate||id):id}
function vehIdFromVan(van){var vv=vehicles().filter(function(x){return String(x.name||'').trim()===String(van||'').trim()||String(x.plate||'').trim()===String(van||'').trim()})[0];return vv?vv.id:''}
function statusTxt(s){return {active:'تعمل',stopped:'متوقفة',maintenance:'صيانة',inactive:'خارج الخدمة'}[s]||s||'-'}
function statusCls(s){return s==='active'?'ok':(s==='maintenance'?'warn':((s==='stopped'||s==='inactive')?'bad':'info'))}
function typeTxt(t){return {downtime:'عدم تشغيل',car_fault:'عطل سيارة',generator_fault:'عطل مولد',expense:'مصروف'}[t]||t||'-'}
function typeCls(t){return (t==='car_fault'||t==='generator_fault')?'bad':(t==='downtime'?'warn':'info')}
function reasonTxt(r){return {car_fault:'عطل سيارة',generator_fault:'عطل مولد',driver_absent:'غياب سائق',groomer_absent:'غياب جرومر',periodic_maintenance:'صيانة دورية',accident:'حادث',other:'سبب آخر'}[r]||r||'-'}
function eventDays(e){return Math.max(1,n(e.days)||1)}
function inPeriodEvent(e){var p=state.period||thisMonth(), v=state.vehicle||'all';return (!p||monthKey(e.date)===p) && (v==='all'||String(e.vehicleId)===String(v))}
function inPeriodSale(r){var p=state.period||thisMonth(), v=state.vehicle||'all';var d=(typeof parseDate==='function')?parseDate(r.date):String(r.date||'');var ok=!p||monthKey(d)===p;var vid=vehIdFromVan(vanOf(r));return ok && (v==='all'||String(vid)===String(v))}
function scopedEvents(){return events().filter(inPeriodEvent)}
function scopedSales(){return recs().filter(inPeriodSale)}
function downDaysFor(id){var p=state.period||thisMonth();return events().filter(function(e){return monthKey(e.date)===p&&String(e.vehicleId)===String(id)&&(e.type==='downtime'||e.type==='car_fault'||e.type==='generator_fault')}).reduce(function(s,e){return s+eventDays(e)},0)}
function readiness(id){var total=daysInMonth(state.period||thisMonth());return total?Math.max(0,Math.min(100,((total-downDaysFor(id))/total)*100)):0}
function summary(){var vs=vehicles(), ev=scopedEvents();var down=ev.filter(function(e){return e.type==='downtime'||e.type==='car_fault'||e.type==='generator_fault'});var costs=ev.reduce(function(s,e){return s+n(e.cost)},0);var open=events().filter(function(e){return (e.type==='car_fault'||e.type==='generator_fault')&&(e.status||'open')!=='closed'}).length;var active=vs.filter(function(v){return (v.status||'active')==='active'}).length;var ready=vs.length?vs.reduce(function(s,v){return s+readiness(v.id)},0)/vs.length:0;return {cars:vs.length,active:active,stopped:vs.length-active,down:down.reduce(function(s,e){return s+eventDays(e)},0),costs:costs,open:open,ready:ready,sales:scopedSales().reduce(function(s,r){return s+n(r.totalInc)},0)}}
function kpi(icon,label,val,sub,color){return '<div class="fleet-kpi" style="--accent:var('+color+')"><span>'+icon+' '+label+'</span><b>'+val+'</b><small>'+sub+'</small></div>'}
function kpis(){var s=summary();return '<div class="fleet-kpis">'+kpi('🚛','إجمالي السيارات',f0(s.cars),'مسجلة في القسم','--purple')+kpi('✅','سيارات تعمل',f0(s.active),'حسب الحالة','--green')+kpi('⛔','سيارات غير عاملة',f0(s.stopped),'متوقفة / صيانة','--red')+kpi('📉','أيام التوقف',f0(s.down),'داخل الفترة','--orange')+kpi('🔧','أعطال مفتوحة',f0(s.open),'سيارة + مولد','--cyan')+kpi('📈','جاهزية الأسطول',Math.round(s.ready)+'%','التشغيل الفعلي','--green')+'</div>'}
function panelHtml(){return '<div id="fleet" class="panel"><div class="fleet-page"><div class="fleet-hero"><div><h2>🚛 إدارة السيارات والأسطول</h2><p>قسم مستقل لتسجيل بيانات السيارات، أعطال السيارة، أعطال المولد، أيام عدم التشغيل، وتحليل جاهزية كل سيارة دون التأثير على التقارير القديمة.</p></div><div class="fleet-icon">🚐</div></div><div class="fleet-toolbar"><label style="color:var(--muted);font:900 12px Cairo">الفترة</label><input id="fleetPeriod" type="month"><label style="color:var(--muted);font:900 12px Cairo">السيارة</label><select id="fleetVehicleFilter"></select><button class="btn btn-primary" data-fleet-action="render">🔄 تحديث</button><button class="btn btn-green" data-fleet-action="seed-demo">➕ بيانات تجربة</button><button class="btn btn-ghost" data-fleet-action="export-csv">📥 تصدير CSV</button></div><div class="fleet-tabs"><button class="fleet-tab-btn active" data-fleet-tab="overview">نظرة عامة</button><button class="fleet-tab-btn" data-fleet-tab="vehicles">بيانات السيارات</button><button class="fleet-tab-btn" data-fleet-tab="entry">إدخال الأعطال والتوقف</button><button class="fleet-tab-btn" data-fleet-tab="reports">التقارير الدورية</button></div><div id="fleetBody"></div></div></div>'}

function ensureFleetDelegation(){
  if(window.__PETATOE_FLEET_DELEGATION__) return;
  window.__PETATOE_FLEET_DELEGATION__=true;
  document.addEventListener('click',function(e){
    var btn=e.target&&e.target.closest?e.target.closest('[data-fleet-action]'):null;
    if(!btn||!btn.closest('#fleet')) return;
    var action=btn.getAttribute('data-fleet-action');
    if(action==='render'){render();return;}
    if(action==='seed-demo'){seedDemo();return;}
    if(action==='export-csv'){exportCSV();return;}
    if(action==='save-vehicle'){saveVehicle();return;}
    if(action==='clear-vehicle-form'){clearVehicleForm();return;}
    if(action==='save-event'){saveEvent();return;}
    if(action==='edit-vehicle'){editVehicle(btn.getAttribute('data-fleet-vehicle-id')||'');return;}
    if(action==='delete-vehicle'){deleteVehicle(btn.getAttribute('data-fleet-vehicle-id')||'');return;}
    if(action==='delete-event'){deleteEvent(btn.getAttribute('data-fleet-event-id')||'');}
  });
}
function ensurePanel(){ensureFleetDelegation();if(!$('fleet')){var page=document.querySelector('section.page')||document.querySelector('.page')||document.body;page.insertAdjacentHTML('beforeend',panelHtml())}setup()}
function ensureNav(){var nav=$('nav')||document.querySelector('nav.nav');if(!nav)return;var b=nav.querySelector('[data-tab="fleet"]');if(!b){b=document.createElement('button');b.dataset.tab='fleet';b.textContent='🚛 إدارة السيارات';nav.insertBefore(b,nav.querySelector('[data-tab="commissions"]')||nav.querySelector('[data-tab="records"]')||null)}b.onclick=function(){window.PETATOERouter.openTab('fleet')};b.classList.remove('locked');b.style.pointerEvents='auto'}
function setup(){var p=$('fleetPeriod');if(p){p.value=state.period||thisMonth();p.onchange=function(){state.period=this.value;render()}}var vf=$('fleetVehicleFilter');if(vf){var cur=state.vehicle||'all';while(vf.firstChild)vf.removeChild(vf.firstChild);var optAll=document.createElement('option');optAll.value='all';optAll.textContent='كل السيارات';vf.appendChild(optAll);vehicles().forEach(function(v){var opt=document.createElement('option');opt.value=String(v.id==null?'':v.id);opt.textContent=String((v.name||v.plate||'')==null?'':(v.name||v.plate||''));vf.appendChild(opt)});vf.value=cur;if(!vf.value)vf.value='all';vf.onchange=function(){state.vehicle=this.value;render()}}document.querySelectorAll('#fleet .fleet-tab-btn').forEach(function(b){b.classList.toggle('active',b.dataset.fleetTab===state.tab);b.onclick=function(){state.tab=this.dataset.fleetTab;setup();renderBody()}})}
function render(){ensurePanel();setup();renderBody()}
function renderBody(){var body=$('fleetBody');if(!body)return;var t=state.tab||'overview';if(t==='overview')fleetSafeRender(body,overviewHtml(),'fleet overview');if(t==='vehicles')fleetSafeRender(body,vehiclesHtml(),'fleet vehicles');if(t==='entry')fleetSafeRender(body,entryHtml(),'fleet entry');if(t==='reports')fleetSafeRender(body,reportsHtml(),'fleet reports');drawCharts()}
function overviewHtml(){var vs=vehicles();return '<div class="fleet-section">'+kpis()+'<div class="fleet-card-list">'+vs.map(function(v){return '<div class="fleet-vehicle-card" style="--accent:var(--cyan)"><h4>'+html(v.name||v.plate)+'</h4><p>السائق: '+html(v.driver||'-')+' | الجرومر: '+html(v.groomer||'-')+'</p><span class="fleet-status '+statusCls(v.status)+'">'+statusTxt(v.status)+'</span><div class="fleet-card-metrics"><div><span>الجاهزية</span><b>'+Math.round(readiness(v.id))+'%</b></div><div><span>أيام التوقف</span><b>'+f0(downDaysFor(v.id))+'</b></div><div><span>مبيعات الفترة</span><b>'+cash(scopedSales().filter(function(r){return vehIdFromVan(vanOf(r))===v.id}).reduce(function(s,r){return s+n(r.totalInc)},0))+'</b></div><div><span>الأعطال</span><b>'+f0(events().filter(function(e){return e.vehicleId===v.id&&(e.type==='car_fault'||e.type==='generator_fault')}).length)+'</b></div></div></div>'}).join('')+'</div><div class="fleet-grid"><div class="fleet-panel"><h3>📊 أسباب التوقف</h3><p>توزيع أسباب عدم التشغيل داخل الفترة.</p><div class="fleet-chart sm"><canvas id="fleetReasonChart"></canvas></div></div><div class="fleet-panel"><h3>📈 جاهزية السيارات</h3><p>نسبة الجاهزية التشغيلية لكل سيارة.</p><div class="fleet-chart sm"><canvas id="fleetReadyChart"></canvas></div></div></div></div>'}
function vehiclesHtml(){var vs=vehicles();return '<div class="fleet-section"><div class="fleet-panel"><h3>🚐 إضافة / تعديل سيارة</h3><p>البيانات محفوظة محلياً داخل المتصفح ولا تغير بيانات المبيعات القديمة.</p><div class="fleet-form"><input id="flId" type="hidden"><div><label>اسم السيارة</label><input id="flName" placeholder="VAN A - AXB 2558"></div><div><label>رقم اللوحة</label><input id="flPlate"></div><div><label>السائق الأساسي</label><input id="flDriver"></div><div><label>الجرومر</label><input id="flGroomer"></div><div><label>الموديل</label><input id="flModel"></div><div><label>سنة الصنع</label><input id="flYear" type="number"></div><div><label>الحالة</label><select id="flStatus"><option value="active">تعمل</option><option value="stopped">متوقفة</option><option value="maintenance">صيانة</option><option value="inactive">خارج الخدمة</option></select></div><div><label>بداية التشغيل</label><input id="flStart" type="date"></div><div class="full"><label>ملاحظات</label><textarea id="flNotes"></textarea></div></div><div class="fleet-actions"><button class="btn btn-green" data-fleet-action="save-vehicle">💾 حفظ السيارة</button><button class="btn btn-ghost" data-fleet-action="clear-vehicle-form">تفريغ</button></div></div><div class="fleet-panel"><h3>📋 بيانات السيارات</h3><div class="fleet-table"><table><thead><tr><th>#</th><th>السيارة</th><th>اللوحة</th><th>السائق</th><th>الجرومر</th><th>الحالة</th><th>الجاهزية</th><th>إجراء</th></tr></thead><tbody>'+vs.map(function(v,i){return '<tr><td>'+f0(i+1)+'</td><td>'+html(v.name)+'</td><td>'+html(v.plate)+'</td><td>'+html(v.driver||'-')+'</td><td>'+html(v.groomer||'-')+'</td><td><span class="fleet-status '+statusCls(v.status)+'">'+statusTxt(v.status)+'</span></td><td>'+Math.round(readiness(v.id))+'%</td><td><button class="fleet-row-btn" data-fleet-action="edit-vehicle" data-fleet-vehicle-id="'+html(v.id)+'">تعديل</button><button class="fleet-row-btn danger" data-fleet-action="delete-vehicle" data-fleet-vehicle-id="'+html(v.id)+'">حذف</button></td></tr>'}).join('')+'</tbody></table></div></div></div>'}
function entryHtml(){return '<div class="fleet-section"><div class="fleet-panel"><h3>🛠️ تسجيل عطل / توقف / مصروف</h3><p>سجل أيام عدم التشغيل بسبب عطل سيارة أو مولد أو غياب موظف أو صيانة.</p><div class="fleet-form"><div><label>التاريخ</label><input id="evDate" type="date" value="'+petBlock5491_today()+'"></div><div><label>السيارة</label><select id="evVehicle">'+vehicles().map(function(v){return '<option value="'+html(v.id)+'">'+html(v.name||v.plate)+'</option>'}).join('')+'</select></div><div><label>نوع التسجيل</label><select id="evType"><option value="downtime">عدم تشغيل</option><option value="car_fault">عطل سيارة</option><option value="generator_fault">عطل مولد</option><option value="expense">مصروف</option></select></div><div><label>السبب</label><select id="evReason"><option value="car_fault">عطل سيارة</option><option value="generator_fault">عطل مولد</option><option value="driver_absent">غياب سائق</option><option value="groomer_absent">غياب جرومر</option><option value="periodic_maintenance">صيانة دورية</option><option value="accident">حادث</option><option value="other">سبب آخر</option></select></div><div><label>أيام التوقف</label><input id="evDays" type="number" min="1" value="1"></div><div><label>التكلفة</label><input id="evCost" type="number" min="0" value="0"></div><div><label>الحالة</label><select id="evStatus"><option value="open">مفتوح</option><option value="closed">مغلق</option></select></div><div class="wide"><label>وصف / ملاحظات</label><input id="evDesc" placeholder="وصف العطل أو سبب التوقف"></div></div><div class="fleet-actions"><button class="btn btn-green" data-fleet-action="save-event">💾 حفظ التسجيل</button></div></div><div class="fleet-panel"><h3>📚 سجل الأعطال والتوقف</h3>'+eventsTable(scopedEvents())+'</div></div>'}
function eventsTable(arr){return '<div class="fleet-table"><table><thead><tr><th>#</th><th>التاريخ</th><th>السيارة</th><th>النوع</th><th>السبب</th><th>الأيام</th><th>التكلفة</th><th>الحالة</th><th>الوصف</th><th>إجراء</th></tr></thead><tbody>'+arr.map(function(e,i){return '<tr><td>'+f0(i+1)+'</td><td>'+html(e.date)+'</td><td>'+html(vehName(e.vehicleId))+'</td><td><span class="fleet-status '+typeCls(e.type)+'">'+typeTxt(e.type)+'</span></td><td>'+reasonTxt(e.reason)+'</td><td>'+f0(eventDays(e))+'</td><td>'+cash(e.cost||0)+'</td><td>'+(e.status==='closed'?'مغلق':'مفتوح')+'</td><td>'+html(e.desc||'-')+'</td><td><button class="fleet-row-btn danger" data-fleet-action="delete-event" data-fleet-event-id="'+html(e.id)+'">حذف</button></td></tr>'}).join('')+(arr.length?'':'<tr><td colspan="10">لا توجد بيانات في الفترة المحددة.</td></tr>')+'</tbody></table></div>'}
function reportsHtml(){var ev=scopedEvents(), vs=vehicles();var byCar=vs.map(function(v){var list=ev.filter(function(e){return e.vehicleId===v.id});return {name:v.name||v.plate,down:list.reduce(function(s,e){return s+((e.type==='expense')?0:eventDays(e))},0),faults:list.filter(function(e){return e.type==='car_fault'||e.type==='generator_fault'}).length,cost:list.reduce(function(s,e){return s+n(e.cost)},0),ready:readiness(v.id)}}).sort(function(a,b){return b.down-a.down});return '<div class="fleet-section">'+kpis()+'<div class="fleet-grid"><div class="fleet-panel"><h3>📉 تقرير التوقف حسب السيارة</h3><p>عدد أيام التوقف والتكلفة والجاهزية.</p><div class="fleet-table compact"><table><thead><tr><th>السيارة</th><th>أيام التوقف</th><th>الأعطال</th><th>التكلفة</th><th>الجاهزية</th></tr></thead><tbody>'+byCar.map(function(r){return '<tr><td>'+html(r.name)+'</td><td>'+f0(r.down)+'</td><td>'+f0(r.faults)+'</td><td>'+cash(r.cost)+'</td><td>'+Math.round(r.ready)+'%</td></tr>'}).join('')+'</tbody></table></div></div><div class="fleet-panel"><h3>🥧 تحليل أسباب التوقف</h3><p>تجميع الأسباب المسجلة خلال الفترة.</p><div class="fleet-chart sm"><canvas id="fleetReportReasonChart"></canvas></div></div></div><div class="fleet-panel"><h3>📋 تفاصيل السجل الدوري</h3>'+eventsTable(ev)+'</div><div class="fleet-mini-note">القسم الجديد مستقل تماماً: يعتمد على سجلات الأسطول المحفوظة في Supabase + يقرأ أسماء السيارات من بيانات المبيعات فقط، ولا يعدل أي تقرير أو معادلة قديمة.</div></div>'}
function destroy(id){if(charts[id]){charts[id].destroy();delete charts[id]}}
function makeChart(id,type,data,opts){var el=$(id);if(!el||!window.Chart)return;destroy(id);var cfg={type:type,data:data,options:Object.assign({responsive:true,maintainAspectRatio:false,animation:{duration:650,easing:'easeOutQuart'},plugins:{legend:{labels:{color:getComputedStyle(document.documentElement).getPropertyValue('--text')||'#fff',font:{family:'Cairo',weight:'800'}}}},scales:{x:{ticks:{color:getComputedStyle(document.documentElement).getPropertyValue('--muted')||'#94a3b8',font:{family:'Cairo',weight:'800'}},grid:{color:'rgba(202,226,255,.09)',drawBorder:false}},y:{ticks:{color:getComputedStyle(document.documentElement).getPropertyValue('--muted')||'#94a3b8',font:{family:'Cairo',weight:'800'}},grid:{color:'rgba(202,226,255,.10)',drawBorder:false}}}},opts||{})};if(typeof petNormalizeChartConfig==='function')cfg=petNormalizeChartConfig(cfg);charts[id]=new Chart(el,cfg)}
function reasonData(){var o={};scopedEvents().forEach(function(e){if(e.type!=='expense'){var k=reasonTxt(e.reason||e.type);o[k]=(o[k]||0)+eventDays(e)}});return o}
function drawReason(id){var o=reasonData(), labels=Object.keys(o), vals=labels.map(function(k){return o[k]});makeChart(id,'doughnut',{labels:labels.length?labels:['لا توجد بيانات'],datasets:[{data:vals.length?vals:[1],borderWidth:0}]},{scales:{}})}
function drawCharts(){if($('fleetReasonChart'))drawReason('fleetReasonChart');if($('fleetReportReasonChart'))drawReason('fleetReportReasonChart');if($('fleetReadyChart')){var vs=vehicles();makeChart('fleetReadyChart','bar',{labels:vs.map(function(v){return v.name||v.plate}),datasets:[{label:'جاهزية %',data:vs.map(function(v){return Math.round(readiness(v.id))})}]},{plugins:{legend:{display:false}}})}}
function saveVehicle(){var s=fleetReadStore(), id=($('flId')||{}).value||('custom-'+Date.now());var existing=s.vehicles.filter(function(v){return v.id===id})[0];var v=existing||{id:id};v.name=($('flName')||{}).value||v.name||'';v.plate=($('flPlate')||{}).value||v.plate||v.name;v.driver=($('flDriver')||{}).value||'';v.groomer=($('flGroomer')||{}).value||'';v.model=($('flModel')||{}).value||'';v.year=($('flYear')||{}).value||'';v.status=($('flStatus')||{}).value||'active';v.startDate=($('flStart')||{}).value||'';v.notes=($('flNotes')||{}).value||'';if(!v.name){if(typeof toast==='function')toast('اكتب اسم السيارة أولاً');return}if(!existing)s.vehicles.push(v);if(!fleetWriteStore(s))return;if(typeof toast==='function')toast('تم حفظ بيانات السيارة');clearVehicleForm();render()}
function editVehicle(id){var v=vehById(id);if(!v)return;state.tab='vehicles';render();setTimeout(function(){var map={flId:v.id,flName:v.name,flPlate:v.plate,flDriver:v.driver,flGroomer:v.groomer,flModel:v.model,flYear:v.year,flStatus:v.status||'active',flStart:v.startDate,flNotes:v.notes};Object.keys(map).forEach(function(k){if($(k))$(k).value=map[k]||''});window.scrollTo({top:0,behavior:'smooth'})},0)}
function clearVehicleForm(){['flId','flName','flPlate','flDriver','flGroomer','flModel','flYear','flStart','flNotes'].forEach(function(id){if($(id))$(id).value=''});if($('flStatus'))$('flStatus').value='active'}
function deleteVehicle(id){if(!confirm('حذف السيارة من قسم إدارة الأسطول فقط؟'))return;var s=fleetReadStore();s.vehicles=s.vehicles.filter(function(v){return v.id!==id});s.events=s.events.filter(function(e){return e.vehicleId!==id});if(!fleetWriteStore(s))return;render();if(typeof toast==='function')toast('تم الحذف من قسم الأسطول')}
function saveEvent(){var s=fleetReadStore();var ev={id:'ev-'+Date.now()+'-'+Math.random().toString(16).slice(2),date:($('evDate')||{}).value||petBlock5491_today(),vehicleId:($('evVehicle')||{}).value,type:($('evType')||{}).value||'downtime',reason:($('evReason')||{}).value||'other',days:n(($('evDays')||{}).value)||1,cost:n(($('evCost')||{}).value)||0,status:($('evStatus')||{}).value||'open',desc:($('evDesc')||{}).value||''};if(!ev.vehicleId){if(typeof toast==='function')toast('اختر السيارة أولاً');return}s.events.push(ev);if(!fleetWriteStore(s))return;if(typeof toast==='function')toast('تم حفظ التسجيل');render()}
function deleteEvent(id){var s=fleetReadStore();s.events=s.events.filter(function(e){return e.id!==id});if(!fleetWriteStore(s))return;render();if(typeof toast==='function')toast('تم حذف التسجيل')}
function seedDemo(){var s=fleetReadStore();var v=s.vehicles[0];if(!v){if(typeof toast==='function')toast('لا توجد سيارات لإضافة بيانات تجربة');return}var p=state.period||thisMonth();s.events.push({id:'ev-'+Date.now(),date:p+'-03',vehicleId:v.id,type:'car_fault',reason:'car_fault',days:2,cost:850,status:'closed',desc:'تجربة: عطل سيارة'});if(s.vehicles[1])s.events.push({id:'ev-'+Date.now()+'b',date:p+'-12',vehicleId:s.vehicles[1].id,type:'generator_fault',reason:'generator_fault',days:1,cost:430,status:'open',desc:'تجربة: عطل مولد'});fleetWriteStore(s);render();if(typeof toast==='function')toast('تمت إضافة بيانات تجربة للقسم')}
function csvEscape(x){return '"'+String(x==null?'':x).replace(/"/g,'""')+'"'}
function exportCSV(){var rows=[['date','vehicle','type','reason','days','cost','status','description']].concat(scopedEvents().map(function(e){return [e.date,vehName(e.vehicleId),typeTxt(e.type),reasonTxt(e.reason),eventDays(e),n(e.cost),e.status||'open',e.desc||'']}));var csv=rows.map(function(r){return r.map(csvEscape).join(',')}).join('\n');var blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='PETATOE_Fleet_Report_'+(state.period||thisMonth())+'.csv';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
function patchTab(){if(window.__PETATOE_FLEET_TABCHANGE_BOUND__){window.PETATOEFleetRender=render;return;}window.__PETATOE_FLEET_TABCHANGE_BOUND__=true;document.addEventListener('petatoe:tabchange',function(e){if(e.detail&&e.detail.tabId==='fleet'){ensurePanel();render();}});window.PETATOEFleetRender=render}
function fleetInit(){ensureNav();patchTab();ensurePanel();setup();}
window.PETATOEFleet={render:render,saveVehicle:saveVehicle,editVehicle:editVehicle,deleteVehicle:deleteVehicle,clearVehicleForm:clearVehicleForm,saveEvent:saveEvent,deleteEvent:deleteEvent,seedDemo:seedDemo,exportCSV:exportCSV};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fleetInit);else fleetInit();
setTimeout(function(){ensureNav();},800);
})();